table Date
	lineageTag: 4876398d-0560-5da0-a673-aa9b81845488

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 56f7691d-2dce-5bf7-bc0d-becaf7379283
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column calendar_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 245a83e6-3c65-516f-be73-c294b4fa9708
		summarizeBy: none
		sourceColumn: calendar_date

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: b5a0b6e7-91b5-5f41-b8b3-c0fcea23edfa
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 9c5267a8-2ff2-5a90-9b77-e62a31c6075e
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	partition Date-e69f5c57-81f8-5449-8c47-72da605dc05f = m
		mode: import
		source =
			let
			    Binary = Binary.FromText("ZGF0ZV9rZXksY2FsZW5kYXJfZGF0ZSx5ZWFyLHF1YXJ0ZXIsbW9udGgsbW9udGhfbmFtZQ0KMjAxODA3MDEsMjAxOC0wNy0wMSwyMDE4LDMsNyxKdWx5DQoyMDE4MDgwMSwyMDE4LTA4LTAxLDIwMTgsMyw4LEF1Z3VzdA0KMjAxODA5MDEsMjAxOC0wOS0wMSwyMDE4LDMsOSxTZXB0ZW1iZXINCjIwMTgxMDAxLDIwMTgtMTAtMDEsMjAxOCw0LDEwLE9jdG9iZXINCjIwMTgxMTAxLDIwMTgtMTEtMDEsMjAxOCw0LDExLE5vdmVtYmVyDQoyMDE4MTIwMSwyMDE4LTEyLTAxLDIwMTgsNCwxMixEZWNlbWJlcg0KMjAxOTAxMDEsMjAxOS0wMS0wMSwyMDE5LDEsMSxKYW51YXJ5DQoyMDE5MDIwMSwyMDE5LTAyLTAxLDIwMTksMSwyLEZlYnJ1YXJ5DQoyMDE5MDMwMSwyMDE5LTAzLTAxLDIwMTksMSwzLE1hcmNoDQoyMDE5MDQwMSwyMDE5LTA0LTAxLDIwMTksMiw0LEFwcmlsDQoyMDE5MDUwMSwyMDE5LTA1LTAxLDIwMTksMiw1LE1heQ0KMjAxOTA2MDEsMjAxOS0wNi0wMSwyMDE5LDIsNixKdW5lDQoyMDE5MDcwMSwyMDE5LTA3LTAxLDIwMTksMyw3LEp1bHkNCjIwMTkwODAxLDIwMTktMDgtMDEsMjAxOSwzLDgsQXVndXN0DQoyMDE5MDkwMSwyMDE5LTA5LTAxLDIwMTksMyw5LFNlcHRlbWJlcg0KMjAxOTEwMDEsMjAxOS0xMC0wMSwyMDE5LDQsMTAsT2N0b2Jlcg0KMjAxOTExMDEsMjAxOS0xMS0wMSwyMDE5LDQsMTEsTm92ZW1iZXINCjIwMTkxMjAxLDIwMTktMTItMDEsMjAxOSw0LDEyLERlY2VtYmVyDQoyMDIwMDEwMSwyMDIwLTAxLTAxLDIwMjAsMSwxLEphbnVhcnkNCjIwMjAwMjAxLDIwMjAtMDItMDEsMjAyMCwxLDIsRmVicnVhcnkNCjIwMjAwMzAxLDIwMjAtMDMtMDEsMjAyMCwxLDMsTWFyY2gNCjIwMjAwNDAxLDIwMjAtMDQtMDEsMjAyMCwyLDQsQXByaWwNCjIwMjAwNTAxLDIwMjAtMDUtMDEsMjAyMCwyLDUsTWF5DQoyMDIwMDYwMSwyMDIwLTA2LTAxLDIwMjAsMiw2LEp1bmUNCjIwMjAwNzAxLDIwMjAtMDctMDEsMjAyMCwzLDcsSnVseQ0KMjAyMDA4MDEsMjAyMC0wOC0wMSwyMDIwLDMsOCxBdWd1c3QNCjIwMjAwOTAxLDIwMjAtMDktMDEsMjAyMCwzLDksU2VwdGVtYmVyDQoyMDIwMTAwMSwyMDIwLTEwLTAxLDIwMjAsNCwxMCxPY3RvYmVyDQoyMDIwMTEwMSwyMDIwLTExLTAxLDIwMjAsNCwxMSxOb3ZlbWJlcg0KMjAyMDEyMDEsMjAyMC0xMi0wMSwyMDIwLDQsMTIsRGVjZW1iZXINCjIwMjEwMTAxLDIwMjEtMDEtMDEsMjAyMSwxLDEsSmFudWFyeQ0KMjAyMTAyMDEsMjAyMS0wMi0wMSwyMDIxLDEsMixGZWJydWFyeQ0KMjAyMTAzMDEsMjAyMS0wMy0wMSwyMDIxLDEsMyxNYXJjaA0KMjAyMTA0MDEsMjAyMS0wNC0wMSwyMDIxLDIsNCxBcHJpbA0KMjAyMTA1MDEsMjAyMS0wNS0wMSwyMDIxLDIsNSxNYXkNCjIwMjEwNjAxLDIwMjEtMDYtMDEsMjAyMSwyLDYsSnVuZQ0KMjAyMTA3MDEsMjAyMS0wNy0wMSwyMDIxLDMsNyxKdWx5DQoyMDIxMDgwMSwyMDIxLTA4LTAxLDIwMjEsMyw4LEF1Z3VzdA0KMjAyMTA5MDEsMjAyMS0wOS0wMSwyMDIxLDMsOSxTZXB0ZW1iZXINCjIwMjExMDAxLDIwMjEtMTAtMDEsMjAyMSw0LDEwLE9jdG9iZXINCjIwMjExMTAxLDIwMjEtMTEtMDEsMjAyMSw0LDExLE5vdmVtYmVyDQoyMDIxMTIwMSwyMDIxLTEyLTAxLDIwMjEsNCwxMixEZWNlbWJlcg0KMjAyMjAxMDEsMjAyMi0wMS0wMSwyMDIyLDEsMSxKYW51YXJ5DQoyMDIyMDIwMSwyMDIyLTAyLTAxLDIwMjIsMSwyLEZlYnJ1YXJ5DQoyMDIyMDMwMSwyMDIyLTAzLTAxLDIwMjIsMSwzLE1hcmNoDQoyMDIyMDQwMSwyMDIyLTA0LTAxLDIwMjIsMiw0LEFwcmlsDQoyMDIyMDUwMSwyMDIyLTA1LTAxLDIwMjIsMiw1LE1heQ0KMjAyMjA2MDEsMjAyMi0wNi0wMSwyMDIyLDIsNixKdW5lDQoyMDIyMDcwMSwyMDIyLTA3LTAxLDIwMjIsMyw3LEp1bHkNCjIwMjIwODAxLDIwMjItMDgtMDEsMjAyMiwzLDgsQXVndXN0DQoyMDIyMDkwMSwyMDIyLTA5LTAxLDIwMjIsMyw5LFNlcHRlbWJlcg0KMjAyMjEwMDEsMjAyMi0xMC0wMSwyMDIyLDQsMTAsT2N0b2Jlcg0KMjAyMjExMDEsMjAyMi0xMS0wMSwyMDIyLDQsMTEsTm92ZW1iZXINCjIwMjIxMjAxLDIwMjItMTItMDEsMjAyMiw0LDEyLERlY2VtYmVyDQoyMDIzMDEwMSwyMDIzLTAxLTAxLDIwMjMsMSwxLEphbnVhcnkNCjIwMjMwMjAxLDIwMjMtMDItMDEsMjAyMywxLDIsRmVicnVhcnkNCjIwMjMwMzAxLDIwMjMtMDMtMDEsMjAyMywxLDMsTWFyY2gNCjIwMjMwNDAxLDIwMjMtMDQtMDEsMjAyMywyLDQsQXByaWwNCjIwMjMwNTAxLDIwMjMtMDUtMDEsMjAyMywyLDUsTWF5DQoyMDIzMDYwMSwyMDIzLTA2LTAxLDIwMjMsMiw2LEp1bmUNCjIwMjMwNzAxLDIwMjMtMDctMDEsMjAyMywzLDcsSnVseQ0KMjAyMzA4MDEsMjAyMy0wOC0wMSwyMDIzLDMsOCxBdWd1c3QNCjIwMjMwOTAxLDIwMjMtMDktMDEsMjAyMywzLDksU2VwdGVtYmVyDQoyMDIzMTAwMSwyMDIzLTEwLTAxLDIwMjMsNCwxMCxPY3RvYmVyDQoyMDIzMTEwMSwyMDIzLTExLTAxLDIwMjMsNCwxMSxOb3ZlbWJlcg0KMjAyMzEyMDEsMjAyMy0xMi0wMSwyMDIzLDQsMTIsRGVjZW1iZXINCjIwMjQwMTAxLDIwMjQtMDEtMDEsMjAyNCwxLDEsSmFudWFyeQ0KMjAyNDAyMDEsMjAyNC0wMi0wMSwyMDI0LDEsMixGZWJydWFyeQ0KMjAyNDAzMDEsMjAyNC0wMy0wMSwyMDI0LDEsMyxNYXJjaA0KMjAyNDA0MDEsMjAyNC0wNC0wMSwyMDI0LDIsNCxBcHJpbA0KMjAyNDA1MDEsMjAyNC0wNS0wMSwyMDI0LDIsNSxNYXkNCjIwMjQwNjAxLDIwMjQtMDYtMDEsMjAyNCwyLDYsSnVuZQ0KMjAyNDA3MDEsMjAyNC0wNy0wMSwyMDI0LDMsNyxKdWx5DQoyMDI0MDgwMSwyMDI0LTA4LTAxLDIwMjQsMyw4LEF1Z3VzdA0KMjAyNDA5MDEsMjAyNC0wOS0wMSwyMDI0LDMsOSxTZXB0ZW1iZXINCjIwMjQxMDAxLDIwMjQtMTAtMDEsMjAyNCw0LDEwLE9jdG9iZXINCjIwMjQxMTAxLDIwMjQtMTEtMDEsMjAyNCw0LDExLE5vdmVtYmVyDQoyMDI0MTIwMSwyMDI0LTEyLTAxLDIwMjQsNCwxMixEZWNlbWJlcg0KMjAyNTAxMDEsMjAyNS0wMS0wMSwyMDI1LDEsMSxKYW51YXJ5DQoyMDI1MDIwMSwyMDI1LTAyLTAxLDIwMjUsMSwyLEZlYnJ1YXJ5DQoyMDI1MDMwMSwyMDI1LTAzLTAxLDIwMjUsMSwzLE1hcmNoDQoyMDI1MDQwMSwyMDI1LTA0LTAxLDIwMjUsMiw0LEFwcmlsDQoyMDI1MDUwMSwyMDI1LTA1LTAxLDIwMjUsMiw1LE1heQ0KMjAyNTA2MDEsMjAyNS0wNi0wMSwyMDI1LDIsNixKdW5lDQoyMDI1MDcwMSwyMDI1LTA3LTAxLDIwMjUsMyw3LEp1bHkNCjIwMjUwODAxLDIwMjUtMDgtMDEsMjAyNSwzLDgsQXVndXN0DQoyMDI1MDkwMSwyMDI1LTA5LTAxLDIwMjUsMyw5LFNlcHRlbWJlcg0KMjAyNTA5MDIsMjAyNS0wOS0wMiwyMDI1LDMsOSxTZXB0ZW1iZXINCjIwMjUwOTAzLDIwMjUtMDktMDMsMjAyNSwzLDksU2VwdGVtYmVyDQoyMDI1MDkwNCwyMDI1LTA5LTA0LDIwMjUsMyw5LFNlcHRlbWJlcg0KMjAyNTA5MDUsMjAyNS0wOS0wNSwyMDI1LDMsOSxTZXB0ZW1iZXINCjIwMjUwOTA2LDIwMjUtMDktMDYsMjAyNSwzLDksU2VwdGVtYmVyDQoyMDI1MDkwNywyMDI1LTA5LTA3LDIwMjUsMyw5LFNlcHRlbWJlcg0KMjAyNTA5MDgsMjAyNS0wOS0wOCwyMDI1LDMsOSxTZXB0ZW1iZXINCjIwMjUwOTA5LDIwMjUtMDktMDksMjAyNSwzLDksU2VwdGVtYmVyDQoyMDI1MDkxMCwyMDI1LTA5LTEwLDIwMjUsMyw5LFNlcHRlbWJlcg0KMjAyNTA5MTEsMjAyNS0wOS0xMSwyMDI1LDMsOSxTZXB0ZW1iZXINCjIwMjUwOTEyLDIwMjUtMDktMTIsMjAyNSwzLDksU2VwdGVtYmVyDQoyMDI1MDkxMywyMDI1LTA5LTEzLDIwMjUsMyw5LFNlcHRlbWJlcg0KMjAyNTA5MTQsMjAyNS0wOS0xNCwyMDI1LDMsOSxTZXB0ZW1iZXINCjIwMjUwOTE1LDIwMjUtMDktMTUsMjAyNSwzLDksU2VwdGVtYmVyDQoyMDI1MTAwMSwyMDI1LTEwLTAxLDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAwMiwyMDI1LTEwLTAyLDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAwMywyMDI1LTEwLTAzLDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAwNCwyMDI1LTEwLTA0LDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAwNSwyMDI1LTEwLTA1LDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAwNiwyMDI1LTEwLTA2LDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAwNywyMDI1LTEwLTA3LDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAwOCwyMDI1LTEwLTA4LDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAwOSwyMDI1LTEwLTA5LDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAxMCwyMDI1LTEwLTEwLDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAxMSwyMDI1LTEwLTExLDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAxMiwyMDI1LTEwLTEyLDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAxMywyMDI1LTEwLTEzLDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAxNCwyMDI1LTEwLTE0LDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTAxNSwyMDI1LTEwLTE1LDIwMjUsNCwxMCxPY3RvYmVyDQoyMDI1MTEwMSwyMDI1LTExLTAxLDIwMjUsNCwxMSxOb3ZlbWJlcg0KMjAyNTExMDIsMjAyNS0xMS0wMiwyMDI1LDQsMTEsTm92ZW1iZXINCjIwMjUxMTAzLDIwMjUtMTEtMDMsMjAyNSw0LDExLE5vdmVtYmVyDQoyMDI1MTEwNCwyMDI1LTExLTA0LDIwMjUsNCwxMSxOb3ZlbWJlcg0KMjAyNTExMDUsMjAyNS0xMS0wNSwyMDI1LDQsMTEsTm92ZW1iZXINCjIwMjUxMTA2LDIwMjUtMTEtMDYsMjAyNSw0LDExLE5vdmVtYmVyDQoyMDI1MTEwNywyMDI1LTExLTA3LDIwMjUsNCwxMSxOb3ZlbWJlcg0KMjAyNTExMDgsMjAyNS0xMS0wOCwyMDI1LDQsMTEsTm92ZW1iZXINCjIwMjUxMTA5LDIwMjUtMTEtMDksMjAyNSw0LDExLE5vdmVtYmVyDQoyMDI1MTExMCwyMDI1LTExLTEwLDIwMjUsNCwxMSxOb3ZlbWJlcg0KMjAyNTExMTEsMjAyNS0xMS0xMSwyMDI1LDQsMTEsTm92ZW1iZXINCjIwMjUxMTEyLDIwMjUtMTEtMTIsMjAyNSw0LDExLE5vdmVtYmVyDQoyMDI1MTExMywyMDI1LTExLTEzLDIwMjUsNCwxMSxOb3ZlbWJlcg0KMjAyNTExMTQsMjAyNS0xMS0xNCwyMDI1LDQsMTEsTm92ZW1iZXINCjIwMjUxMTE1LDIwMjUtMTEtMTUsMjAyNSw0LDExLE5vdmVtYmVyDQoyMDI1MTEyMCwyMDI1LTExLTIwLDIwMjUsNCwxMSxOb3ZlbWJlcg0KMjAyNTEyMDEsMjAyNS0xMi0wMSwyMDI1LDQsMTIsRGVjZW1iZXINCjIwMjUxMjAyLDIwMjUtMTItMDIsMjAyNSw0LDEyLERlY2VtYmVyDQoyMDI1MTIwMywyMDI1LTEyLTAzLDIwMjUsNCwxMixEZWNlbWJlcg0KMjAyNTEyMDQsMjAyNS0xMi0wNCwyMDI1LDQsMTIsRGVjZW1iZXINCjIwMjUxMjA1LDIwMjUtMTItMDUsMjAyNSw0LDEyLERlY2VtYmVyDQoyMDI1MTIwNiwyMDI1LTEyLTA2LDIwMjUsNCwxMixEZWNlbWJlcg0KMjAyNTEyMDcsMjAyNS0xMi0wNywyMDI1LDQsMTIsRGVjZW1iZXINCjIwMjUxMjA4LDIwMjUtMTItMDgsMjAyNSw0LDEyLERlY2VtYmVyDQoyMDI1MTIwOSwyMDI1LTEyLTA5LDIwMjUsNCwxMixEZWNlbWJlcg0KMjAyNTEyMTAsMjAyNS0xMi0xMCwyMDI1LDQsMTIsRGVjZW1iZXINCjIwMjUxMjExLDIwMjUtMTItMTEsMjAyNSw0LDEyLERlY2VtYmVyDQoyMDI1MTIxMiwyMDI1LTEyLTEyLDIwMjUsNCwxMixEZWNlbWJlcg0KMjAyNTEyMTMsMjAyNS0xMi0xMywyMDI1LDQsMTIsRGVjZW1iZXINCjIwMjUxMjE0LDIwMjUtMTItMTQsMjAyNSw0LDEyLERlY2VtYmVyDQoyMDI1MTIxNSwyMDI1LTEyLTE1LDIwMjUsNCwxMixEZWNlbWJlcg0KMjAyNjAxMDEsMjAyNi0wMS0wMSwyMDI2LDEsMSxKYW51YXJ5DQoyMDI2MDEwMiwyMDI2LTAxLTAyLDIwMjYsMSwxLEphbnVhcnkNCjIwMjYwMTAzLDIwMjYtMDEtMDMsMjAyNiwxLDEsSmFudWFyeQ0KMjAyNjAxMDQsMjAyNi0wMS0wNCwyMDI2LDEsMSxKYW51YXJ5DQoyMDI2MDEwNSwyMDI2LTAxLTA1LDIwMjYsMSwxLEphbnVhcnkNCjIwMjYwMTA2LDIwMjYtMDEtMDYsMjAyNiwxLDEsSmFudWFyeQ0KMjAyNjAxMDcsMjAyNi0wMS0wNywyMDI2LDEsMSxKYW51YXJ5DQoyMDI2MDEwOCwyMDI2LTAxLTA4LDIwMjYsMSwxLEphbnVhcnkNCjIwMjYwMTA5LDIwMjYtMDEtMDksMjAyNiwxLDEsSmFudWFyeQ0KMjAyNjAxMTAsMjAyNi0wMS0xMCwyMDI2LDEsMSxKYW51YXJ5DQoyMDI2MDExMSwyMDI2LTAxLTExLDIwMjYsMSwxLEphbnVhcnkNCjIwMjYwMTEyLDIwMjYtMDEtMTIsMjAyNiwxLDEsSmFudWFyeQ0KMjAyNjAxMTMsMjAyNi0wMS0xMywyMDI2LDEsMSxKYW51YXJ5DQoyMDI2MDExNCwyMDI2LTAxLTE0LDIwMjYsMSwxLEphbnVhcnkNCjIwMjYwMTE1LDIwMjYtMDEtMTUsMjAyNiwxLDEsSmFudWFyeQ0KMjAyNjAyMDEsMjAyNi0wMi0wMSwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMDIsMjAyNi0wMi0wMiwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMDMsMjAyNi0wMi0wMywyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMDQsMjAyNi0wMi0wNCwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMDUsMjAyNi0wMi0wNSwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMDYsMjAyNi0wMi0wNiwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMDcsMjAyNi0wMi0wNywyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMDgsMjAyNi0wMi0wOCwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMDksMjAyNi0wMi0wOSwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMTAsMjAyNi0wMi0xMCwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMTEsMjAyNi0wMi0xMSwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMTIsMjAyNi0wMi0xMiwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMTMsMjAyNi0wMi0xMywyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMTQsMjAyNi0wMi0xNCwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMTUsMjAyNi0wMi0xNSwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAyMjAsMjAyNi0wMi0yMCwyMDI2LDEsMixGZWJydWFyeQ0KMjAyNjAzMDEsMjAyNi0wMy0wMSwyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMDIsMjAyNi0wMy0wMiwyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMDMsMjAyNi0wMy0wMywyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMDQsMjAyNi0wMy0wNCwyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMDUsMjAyNi0wMy0wNSwyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMDYsMjAyNi0wMy0wNiwyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMDcsMjAyNi0wMy0wNywyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMDgsMjAyNi0wMy0wOCwyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMDksMjAyNi0wMy0wOSwyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMTAsMjAyNi0wMy0xMCwyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMTEsMjAyNi0wMy0xMSwyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMTIsMjAyNi0wMy0xMiwyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMTMsMjAyNi0wMy0xMywyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMTQsMjAyNi0wMy0xNCwyMDI2LDEsMyxNYXJjaA0KMjAyNjAzMTUsMjAyNi0wMy0xNSwyMDI2LDEsMyxNYXJjaA0KMjAyNjA0MDEsMjAyNi0wNC0wMSwyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MDIsMjAyNi0wNC0wMiwyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MDMsMjAyNi0wNC0wMywyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MDQsMjAyNi0wNC0wNCwyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MDUsMjAyNi0wNC0wNSwyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MDYsMjAyNi0wNC0wNiwyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MDcsMjAyNi0wNC0wNywyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MDgsMjAyNi0wNC0wOCwyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MDksMjAyNi0wNC0wOSwyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MTAsMjAyNi0wNC0xMCwyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MTEsMjAyNi0wNC0xMSwyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MTIsMjAyNi0wNC0xMiwyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MTMsMjAyNi0wNC0xMywyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MTQsMjAyNi0wNC0xNCwyMDI2LDIsNCxBcHJpbA0KMjAyNjA0MTUsMjAyNi0wNC0xNSwyMDI2LDIsNCxBcHJpbA0KMjAyNjA1MDEsMjAyNi0wNS0wMSwyMDI2LDIsNSxNYXkNCjIwMjYwNTAyLDIwMjYtMDUtMDIsMjAyNiwyLDUsTWF5DQoyMDI2MDUwMywyMDI2LTA1LTAzLDIwMjYsMiw1LE1heQ0KMjAyNjA1MDQsMjAyNi0wNS0wNCwyMDI2LDIsNSxNYXkNCjIwMjYwNTA1LDIwMjYtMDUtMDUsMjAyNiwyLDUsTWF5DQoyMDI2MDUwNiwyMDI2LTA1LTA2LDIwMjYsMiw1LE1heQ0KMjAyNjA1MDcsMjAyNi0wNS0wNywyMDI2LDIsNSxNYXkNCjIwMjYwNTA4LDIwMjYtMDUtMDgsMjAyNiwyLDUsTWF5DQoyMDI2MDUwOSwyMDI2LTA1LTA5LDIwMjYsMiw1LE1heQ0KMjAyNjA1MTAsMjAyNi0wNS0xMCwyMDI2LDIsNSxNYXkNCjIwMjYwNTExLDIwMjYtMDUtMTEsMjAyNiwyLDUsTWF5DQoyMDI2MDUxMiwyMDI2LTA1LTEyLDIwMjYsMiw1LE1heQ0KMjAyNjA1MTMsMjAyNi0wNS0xMywyMDI2LDIsNSxNYXkNCjIwMjYwNTE0LDIwMjYtMDUtMTQsMjAyNiwyLDUsTWF5DQoyMDI2MDUxNSwyMDI2LTA1LTE1LDIwMjYsMiw1LE1heQ0KMjAyNjA1MjAsMjAyNi0wNS0yMCwyMDI2LDIsNSxNYXkNCjIwMjYwNjAxLDIwMjYtMDYtMDEsMjAyNiwyLDYsSnVuZQ0KMjAyNjA2MDIsMjAyNi0wNi0wMiwyMDI2LDIsNixKdW5lDQoyMDI2MDYwMywyMDI2LTA2LTAzLDIwMjYsMiw2LEp1bmUNCjIwMjYwNjA0LDIwMjYtMDYtMDQsMjAyNiwyLDYsSnVuZQ0KMjAyNjA2MDUsMjAyNi0wNi0wNSwyMDI2LDIsNixKdW5lDQoyMDI2MDYwNiwyMDI2LTA2LTA2LDIwMjYsMiw2LEp1bmUNCjIwMjYwNjA3LDIwMjYtMDYtMDcsMjAyNiwyLDYsSnVuZQ0KMjAyNjA2MDgsMjAyNi0wNi0wOCwyMDI2LDIsNixKdW5lDQoyMDI2MDYwOSwyMDI2LTA2LTA5LDIwMjYsMiw2LEp1bmUNCjIwMjYwNjEwLDIwMjYtMDYtMTAsMjAyNiwyLDYsSnVuZQ0KMjAyNjA2MTEsMjAyNi0wNi0xMSwyMDI2LDIsNixKdW5lDQoyMDI2MDYxMiwyMDI2LTA2LTEyLDIwMjYsMiw2LEp1bmUNCjIwMjYwNjEzLDIwMjYtMDYtMTMsMjAyNiwyLDYsSnVuZQ0KMjAyNjA2MTQsMjAyNi0wNi0xNCwyMDI2LDIsNixKdW5lDQoyMDI2MDYxNSwyMDI2LTA2LTE1LDIwMjYsMiw2LEp1bmUNCjIwMjYwNzAxLDIwMjYtMDctMDEsMjAyNiwzLDcsSnVseQ0KMjAyNjA3MDIsMjAyNi0wNy0wMiwyMDI2LDMsNyxKdWx5DQoyMDI2MDcwMywyMDI2LTA3LTAzLDIwMjYsMyw3LEp1bHkNCjIwMjYwNzA0LDIwMjYtMDctMDQsMjAyNiwzLDcsSnVseQ0KMjAyNjA3MDUsMjAyNi0wNy0wNSwyMDI2LDMsNyxKdWx5DQoyMDI2MDcwNiwyMDI2LTA3LTA2LDIwMjYsMyw3LEp1bHkNCjIwMjYwNzA3LDIwMjYtMDctMDcsMjAyNiwzLDcsSnVseQ0KMjAyNjA3MDgsMjAyNi0wNy0wOCwyMDI2LDMsNyxKdWx5DQoyMDI2MDcwOSwyMDI2LTA3LTA5LDIwMjYsMyw3LEp1bHkNCjIwMjYwNzEwLDIwMjYtMDctMTAsMjAyNiwzLDcsSnVseQ0KMjAyNjA3MTEsMjAyNi0wNy0xMSwyMDI2LDMsNyxKdWx5DQoyMDI2MDcxMiwyMDI2LTA3LTEyLDIwMjYsMyw3LEp1bHkNCjIwMjYwNzEzLDIwMjYtMDctMTMsMjAyNiwzLDcsSnVseQ0KMjAyNjA3MTQsMjAyNi0wNy0xNCwyMDI2LDMsNyxKdWx5DQoyMDI2MDcxNSwyMDI2LTA3LTE1LDIwMjYsMyw3LEp1bHkNCjIwMjYwODAxLDIwMjYtMDgtMDEsMjAyNiwzLDgsQXVndXN0DQoyMDI2MDgwMiwyMDI2LTA4LTAyLDIwMjYsMyw4LEF1Z3VzdA0KMjAyNjA4MDMsMjAyNi0wOC0wMywyMDI2LDMsOCxBdWd1c3QNCjIwMjYwODA0LDIwMjYtMDgtMDQsMjAyNiwzLDgsQXVndXN0DQoyMDI2MDgwNSwyMDI2LTA4LTA1LDIwMjYsMyw4LEF1Z3VzdA0KMjAyNjA4MDYsMjAyNi0wOC0wNiwyMDI2LDMsOCxBdWd1c3QNCjIwMjYwODA3LDIwMjYtMDgtMDcsMjAyNiwzLDgsQXVndXN0DQoyMDI2MDgwOCwyMDI2LTA4LTA4LDIwMjYsMyw4LEF1Z3VzdA0KMjAyNjA4MDksMjAyNi0wOC0wOSwyMDI2LDMsOCxBdWd1c3QNCjIwMjYwODEwLDIwMjYtMDgtMTAsMjAyNiwzLDgsQXVndXN0DQoyMDI2MDgxMSwyMDI2LTA4LTExLDIwMjYsMyw4LEF1Z3VzdA0KMjAyNjA4MTIsMjAyNi0wOC0xMiwyMDI2LDMsOCxBdWd1c3QNCjIwMjYwODEzLDIwMjYtMDgtMTMsMjAyNiwzLDgsQXVndXN0DQoyMDI2MDgxNCwyMDI2LTA4LTE0LDIwMjYsMyw4LEF1Z3VzdA0KMjAyNjA4MTUsMjAyNi0wOC0xNSwyMDI2LDMsOCxBdWd1c3QNCjIwMjYwODIwLDIwMjYtMDgtMjAsMjAyNiwzLDgsQXVndXN0DQo=", BinaryEncoding.Base64),
			    Raw = Csv.Document(Binary, [Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Raw, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Headers, {"date_key", "calendar_date", "year", "month_name"}),
			    Typed = Table.TransformColumnTypes(Selected, {{"date_key", Int64.Type}, {"calendar_date", type date}, {"year", Int64.Type}, {"month_name", type text}}, "en-AU")
			in
			    Typed

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
