table Date
	lineageTag: 4876398d-0560-5da0-a673-aa9b81845488

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 56f7691d-2dce-5bf7-bc0d-becaf7379283
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column calendar_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 245a83e6-3c65-516f-be73-c294b4fa9708
		summarizeBy: none
		sourceColumn: calendar_date

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: b5a0b6e7-91b5-5f41-b8b3-c0fcea23edfa
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 9c5267a8-2ff2-5a90-9b77-e62a31c6075e
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	partition Date-e69f5c57-81f8-5449-8c47-72da605dc05f = m
		mode: import
		source =
			let
			    Binary = Binary.FromText("ZGF0ZV9rZXksY2FsZW5kYXJfZGF0ZSx5ZWFyLHF1YXJ0ZXIsbW9udGgsbW9udGhfbmFtZQoyMDE4MDcwMSwyMDE4LTA3LTAxLDIwMTgsMyw3LEp1bHkKMjAxODA4MDEsMjAxOC0wOC0wMSwyMDE4LDMsOCxBdWd1c3QKMjAxODA5MDEsMjAxOC0wOS0wMSwyMDE4LDMsOSxTZXB0ZW1iZXIKMjAxODEwMDEsMjAxOC0xMC0wMSwyMDE4LDQsMTAsT2N0b2JlcgoyMDE4MTEwMSwyMDE4LTExLTAxLDIwMTgsNCwxMSxOb3ZlbWJlcgoyMDE4MTIwMSwyMDE4LTEyLTAxLDIwMTgsNCwxMixEZWNlbWJlcgoyMDE5MDEwMSwyMDE5LTAxLTAxLDIwMTksMSwxLEphbnVhcnkKMjAxOTAyMDEsMjAxOS0wMi0wMSwyMDE5LDEsMixGZWJydWFyeQoyMDE5MDMwMSwyMDE5LTAzLTAxLDIwMTksMSwzLE1hcmNoCjIwMTkwNDAxLDIwMTktMDQtMDEsMjAxOSwyLDQsQXByaWwKMjAxOTA1MDEsMjAxOS0wNS0wMSwyMDE5LDIsNSxNYXkKMjAxOTA2MDEsMjAxOS0wNi0wMSwyMDE5LDIsNixKdW5lCjIwMTkwNzAxLDIwMTktMDctMDEsMjAxOSwzLDcsSnVseQoyMDE5MDgwMSwyMDE5LTA4LTAxLDIwMTksMyw4LEF1Z3VzdAoyMDE5MDkwMSwyMDE5LTA5LTAxLDIwMTksMyw5LFNlcHRlbWJlcgoyMDE5MTAwMSwyMDE5LTEwLTAxLDIwMTksNCwxMCxPY3RvYmVyCjIwMTkxMTAxLDIwMTktMTEtMDEsMjAxOSw0LDExLE5vdmVtYmVyCjIwMTkxMjAxLDIwMTktMTItMDEsMjAxOSw0LDEyLERlY2VtYmVyCjIwMjAwMTAxLDIwMjAtMDEtMDEsMjAyMCwxLDEsSmFudWFyeQoyMDIwMDIwMSwyMDIwLTAyLTAxLDIwMjAsMSwyLEZlYnJ1YXJ5CjIwMjAwMzAxLDIwMjAtMDMtMDEsMjAyMCwxLDMsTWFyY2gKMjAyMDA0MDEsMjAyMC0wNC0wMSwyMDIwLDIsNCxBcHJpbAoyMDIwMDUwMSwyMDIwLTA1LTAxLDIwMjAsMiw1LE1heQoyMDIwMDYwMSwyMDIwLTA2LTAxLDIwMjAsMiw2LEp1bmUKMjAyMDA3MDEsMjAyMC0wNy0wMSwyMDIwLDMsNyxKdWx5CjIwMjAwODAxLDIwMjAtMDgtMDEsMjAyMCwzLDgsQXVndXN0CjIwMjAwOTAxLDIwMjAtMDktMDEsMjAyMCwzLDksU2VwdGVtYmVyCjIwMjAxMDAxLDIwMjAtMTAtMDEsMjAyMCw0LDEwLE9jdG9iZXIKMjAyMDExMDEsMjAyMC0xMS0wMSwyMDIwLDQsMTEsTm92ZW1iZXIKMjAyMDEyMDEsMjAyMC0xMi0wMSwyMDIwLDQsMTIsRGVjZW1iZXIKMjAyMTAxMDEsMjAyMS0wMS0wMSwyMDIxLDEsMSxKYW51YXJ5CjIwMjEwMjAxLDIwMjEtMDItMDEsMjAyMSwxLDIsRmVicnVhcnkKMjAyMTAzMDEsMjAyMS0wMy0wMSwyMDIxLDEsMyxNYXJjaAoyMDIxMDQwMSwyMDIxLTA0LTAxLDIwMjEsMiw0LEFwcmlsCjIwMjEwNTAxLDIwMjEtMDUtMDEsMjAyMSwyLDUsTWF5CjIwMjEwNjAxLDIwMjEtMDYtMDEsMjAyMSwyLDYsSnVuZQoyMDIxMDcwMSwyMDIxLTA3LTAxLDIwMjEsMyw3LEp1bHkKMjAyMTA4MDEsMjAyMS0wOC0wMSwyMDIxLDMsOCxBdWd1c3QKMjAyMTA5MDEsMjAyMS0wOS0wMSwyMDIxLDMsOSxTZXB0ZW1iZXIKMjAyMTEwMDEsMjAyMS0xMC0wMSwyMDIxLDQsMTAsT2N0b2JlcgoyMDIxMTEwMSwyMDIxLTExLTAxLDIwMjEsNCwxMSxOb3ZlbWJlcgoyMDIxMTIwMSwyMDIxLTEyLTAxLDIwMjEsNCwxMixEZWNlbWJlcgoyMDIyMDEwMSwyMDIyLTAxLTAxLDIwMjIsMSwxLEphbnVhcnkKMjAyMjAyMDEsMjAyMi0wMi0wMSwyMDIyLDEsMixGZWJydWFyeQoyMDIyMDMwMSwyMDIyLTAzLTAxLDIwMjIsMSwzLE1hcmNoCjIwMjIwNDAxLDIwMjItMDQtMDEsMjAyMiwyLDQsQXByaWwKMjAyMjA1MDEsMjAyMi0wNS0wMSwyMDIyLDIsNSxNYXkKMjAyMjA2MDEsMjAyMi0wNi0wMSwyMDIyLDIsNixKdW5lCjIwMjIwNzAxLDIwMjItMDctMDEsMjAyMiwzLDcsSnVseQoyMDIyMDgwMSwyMDIyLTA4LTAxLDIwMjIsMyw4LEF1Z3VzdAoyMDIyMDkwMSwyMDIyLTA5LTAxLDIwMjIsMyw5LFNlcHRlbWJlcgoyMDIyMTAwMSwyMDIyLTEwLTAxLDIwMjIsNCwxMCxPY3RvYmVyCjIwMjIxMTAxLDIwMjItMTEtMDEsMjAyMiw0LDExLE5vdmVtYmVyCjIwMjIxMjAxLDIwMjItMTItMDEsMjAyMiw0LDEyLERlY2VtYmVyCjIwMjMwMTAxLDIwMjMtMDEtMDEsMjAyMywxLDEsSmFudWFyeQoyMDIzMDIwMSwyMDIzLTAyLTAxLDIwMjMsMSwyLEZlYnJ1YXJ5CjIwMjMwMzAxLDIwMjMtMDMtMDEsMjAyMywxLDMsTWFyY2gKMjAyMzA0MDEsMjAyMy0wNC0wMSwyMDIzLDIsNCxBcHJpbAoyMDIzMDUwMSwyMDIzLTA1LTAxLDIwMjMsMiw1LE1heQoyMDIzMDYwMSwyMDIzLTA2LTAxLDIwMjMsMiw2LEp1bmUKMjAyMzA3MDEsMjAyMy0wNy0wMSwyMDIzLDMsNyxKdWx5CjIwMjMwODAxLDIwMjMtMDgtMDEsMjAyMywzLDgsQXVndXN0CjIwMjMwOTAxLDIwMjMtMDktMDEsMjAyMywzLDksU2VwdGVtYmVyCjIwMjMxMDAxLDIwMjMtMTAtMDEsMjAyMyw0LDEwLE9jdG9iZXIKMjAyMzExMDEsMjAyMy0xMS0wMSwyMDIzLDQsMTEsTm92ZW1iZXIKMjAyMzEyMDEsMjAyMy0xMi0wMSwyMDIzLDQsMTIsRGVjZW1iZXIKMjAyNDAxMDEsMjAyNC0wMS0wMSwyMDI0LDEsMSxKYW51YXJ5CjIwMjQwMjAxLDIwMjQtMDItMDEsMjAyNCwxLDIsRmVicnVhcnkKMjAyNDAzMDEsMjAyNC0wMy0wMSwyMDI0LDEsMyxNYXJjaAoyMDI0MDQwMSwyMDI0LTA0LTAxLDIwMjQsMiw0LEFwcmlsCjIwMjQwNTAxLDIwMjQtMDUtMDEsMjAyNCwyLDUsTWF5CjIwMjQwNjAxLDIwMjQtMDYtMDEsMjAyNCwyLDYsSnVuZQoyMDI0MDcwMSwyMDI0LTA3LTAxLDIwMjQsMyw3LEp1bHkKMjAyNDA4MDEsMjAyNC0wOC0wMSwyMDI0LDMsOCxBdWd1c3QKMjAyNDA5MDEsMjAyNC0wOS0wMSwyMDI0LDMsOSxTZXB0ZW1iZXIKMjAyNDEwMDEsMjAyNC0xMC0wMSwyMDI0LDQsMTAsT2N0b2JlcgoyMDI0MTEwMSwyMDI0LTExLTAxLDIwMjQsNCwxMSxOb3ZlbWJlcgoyMDI0MTIwMSwyMDI0LTEyLTAxLDIwMjQsNCwxMixEZWNlbWJlcgoyMDI1MDEwMSwyMDI1LTAxLTAxLDIwMjUsMSwxLEphbnVhcnkKMjAyNTAyMDEsMjAyNS0wMi0wMSwyMDI1LDEsMixGZWJydWFyeQoyMDI1MDMwMSwyMDI1LTAzLTAxLDIwMjUsMSwzLE1hcmNoCjIwMjUwNDAxLDIwMjUtMDQtMDEsMjAyNSwyLDQsQXByaWwKMjAyNTA1MDEsMjAyNS0wNS0wMSwyMDI1LDIsNSxNYXkKMjAyNTA2MDEsMjAyNS0wNi0wMSwyMDI1LDIsNixKdW5lCjIwMjUwNzAxLDIwMjUtMDctMDEsMjAyNSwzLDcsSnVseQoyMDI1MDgwMSwyMDI1LTA4LTAxLDIwMjUsMyw4LEF1Z3VzdAoyMDI1MDkwMSwyMDI1LTA5LTAxLDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkwMiwyMDI1LTA5LTAyLDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkwMywyMDI1LTA5LTAzLDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkwNCwyMDI1LTA5LTA0LDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkwNSwyMDI1LTA5LTA1LDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkwNiwyMDI1LTA5LTA2LDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkwNywyMDI1LTA5LTA3LDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkwOCwyMDI1LTA5LTA4LDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkwOSwyMDI1LTA5LTA5LDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkxMCwyMDI1LTA5LTEwLDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkxMSwyMDI1LTA5LTExLDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkxMiwyMDI1LTA5LTEyLDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkxMywyMDI1LTA5LTEzLDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkxNCwyMDI1LTA5LTE0LDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MDkxNSwyMDI1LTA5LTE1LDIwMjUsMyw5LFNlcHRlbWJlcgoyMDI1MTAwMSwyMDI1LTEwLTAxLDIwMjUsNCwxMCxPY3RvYmVyCjIwMjUxMDAyLDIwMjUtMTAtMDIsMjAyNSw0LDEwLE9jdG9iZXIKMjAyNTEwMDMsMjAyNS0xMC0wMywyMDI1LDQsMTAsT2N0b2JlcgoyMDI1MTAwNCwyMDI1LTEwLTA0LDIwMjUsNCwxMCxPY3RvYmVyCjIwMjUxMDA1LDIwMjUtMTAtMDUsMjAyNSw0LDEwLE9jdG9iZXIKMjAyNTEwMDYsMjAyNS0xMC0wNiwyMDI1LDQsMTAsT2N0b2JlcgoyMDI1MTAwNywyMDI1LTEwLTA3LDIwMjUsNCwxMCxPY3RvYmVyCjIwMjUxMDA4LDIwMjUtMTAtMDgsMjAyNSw0LDEwLE9jdG9iZXIKMjAyNTEwMDksMjAyNS0xMC0wOSwyMDI1LDQsMTAsT2N0b2JlcgoyMDI1MTAxMCwyMDI1LTEwLTEwLDIwMjUsNCwxMCxPY3RvYmVyCjIwMjUxMDExLDIwMjUtMTAtMTEsMjAyNSw0LDEwLE9jdG9iZXIKMjAyNTEwMTIsMjAyNS0xMC0xMiwyMDI1LDQsMTAsT2N0b2JlcgoyMDI1MTAxMywyMDI1LTEwLTEzLDIwMjUsNCwxMCxPY3RvYmVyCjIwMjUxMDE0LDIwMjUtMTAtMTQsMjAyNSw0LDEwLE9jdG9iZXIKMjAyNTEwMTUsMjAyNS0xMC0xNSwyMDI1LDQsMTAsT2N0b2JlcgoyMDI1MTEwMSwyMDI1LTExLTAxLDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTEwMiwyMDI1LTExLTAyLDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTEwMywyMDI1LTExLTAzLDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTEwNCwyMDI1LTExLTA0LDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTEwNSwyMDI1LTExLTA1LDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTEwNiwyMDI1LTExLTA2LDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTEwNywyMDI1LTExLTA3LDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTEwOCwyMDI1LTExLTA4LDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTEwOSwyMDI1LTExLTA5LDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTExMCwyMDI1LTExLTEwLDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTExMSwyMDI1LTExLTExLDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTExMiwyMDI1LTExLTEyLDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTExMywyMDI1LTExLTEzLDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTExNCwyMDI1LTExLTE0LDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTExNSwyMDI1LTExLTE1LDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTEyMCwyMDI1LTExLTIwLDIwMjUsNCwxMSxOb3ZlbWJlcgoyMDI1MTIwMSwyMDI1LTEyLTAxLDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIwMiwyMDI1LTEyLTAyLDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIwMywyMDI1LTEyLTAzLDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIwNCwyMDI1LTEyLTA0LDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIwNSwyMDI1LTEyLTA1LDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIwNiwyMDI1LTEyLTA2LDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIwNywyMDI1LTEyLTA3LDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIwOCwyMDI1LTEyLTA4LDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIwOSwyMDI1LTEyLTA5LDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIxMCwyMDI1LTEyLTEwLDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIxMSwyMDI1LTEyLTExLDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIxMiwyMDI1LTEyLTEyLDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIxMywyMDI1LTEyLTEzLDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIxNCwyMDI1LTEyLTE0LDIwMjUsNCwxMixEZWNlbWJlcgoyMDI1MTIxNSwyMDI1LTEyLTE1LDIwMjUsNCwxMixEZWNlbWJlcgoyMDI2MDEwMSwyMDI2LTAxLTAxLDIwMjYsMSwxLEphbnVhcnkKMjAyNjAxMDIsMjAyNi0wMS0wMiwyMDI2LDEsMSxKYW51YXJ5CjIwMjYwMTAzLDIwMjYtMDEtMDMsMjAyNiwxLDEsSmFudWFyeQoyMDI2MDEwNCwyMDI2LTAxLTA0LDIwMjYsMSwxLEphbnVhcnkKMjAyNjAxMDUsMjAyNi0wMS0wNSwyMDI2LDEsMSxKYW51YXJ5CjIwMjYwMTA2LDIwMjYtMDEtMDYsMjAyNiwxLDEsSmFudWFyeQoyMDI2MDEwNywyMDI2LTAxLTA3LDIwMjYsMSwxLEphbnVhcnkKMjAyNjAxMDgsMjAyNi0wMS0wOCwyMDI2LDEsMSxKYW51YXJ5CjIwMjYwMTA5LDIwMjYtMDEtMDksMjAyNiwxLDEsSmFudWFyeQoyMDI2MDExMCwyMDI2LTAxLTEwLDIwMjYsMSwxLEphbnVhcnkKMjAyNjAxMTEsMjAyNi0wMS0xMSwyMDI2LDEsMSxKYW51YXJ5CjIwMjYwMTEyLDIwMjYtMDEtMTIsMjAyNiwxLDEsSmFudWFyeQoyMDI2MDExMywyMDI2LTAxLTEzLDIwMjYsMSwxLEphbnVhcnkKMjAyNjAxMTQsMjAyNi0wMS0xNCwyMDI2LDEsMSxKYW51YXJ5CjIwMjYwMTE1LDIwMjYtMDEtMTUsMjAyNiwxLDEsSmFudWFyeQoyMDI2MDIwMSwyMDI2LTAyLTAxLDIwMjYsMSwyLEZlYnJ1YXJ5CjIwMjYwMjAyLDIwMjYtMDItMDIsMjAyNiwxLDIsRmVicnVhcnkKMjAyNjAyMDMsMjAyNi0wMi0wMywyMDI2LDEsMixGZWJydWFyeQoyMDI2MDIwNCwyMDI2LTAyLTA0LDIwMjYsMSwyLEZlYnJ1YXJ5CjIwMjYwMjA1LDIwMjYtMDItMDUsMjAyNiwxLDIsRmVicnVhcnkKMjAyNjAyMDYsMjAyNi0wMi0wNiwyMDI2LDEsMixGZWJydWFyeQoyMDI2MDIwNywyMDI2LTAyLTA3LDIwMjYsMSwyLEZlYnJ1YXJ5CjIwMjYwMjA4LDIwMjYtMDItMDgsMjAyNiwxLDIsRmVicnVhcnkKMjAyNjAyMDksMjAyNi0wMi0wOSwyMDI2LDEsMixGZWJydWFyeQoyMDI2MDIxMCwyMDI2LTAyLTEwLDIwMjYsMSwyLEZlYnJ1YXJ5CjIwMjYwMjExLDIwMjYtMDItMTEsMjAyNiwxLDIsRmVicnVhcnkKMjAyNjAyMTIsMjAyNi0wMi0xMiwyMDI2LDEsMixGZWJydWFyeQoyMDI2MDIxMywyMDI2LTAyLTEzLDIwMjYsMSwyLEZlYnJ1YXJ5CjIwMjYwMjE0LDIwMjYtMDItMTQsMjAyNiwxLDIsRmVicnVhcnkKMjAyNjAyMTUsMjAyNi0wMi0xNSwyMDI2LDEsMixGZWJydWFyeQoyMDI2MDIyMCwyMDI2LTAyLTIwLDIwMjYsMSwyLEZlYnJ1YXJ5CjIwMjYwMzAxLDIwMjYtMDMtMDEsMjAyNiwxLDMsTWFyY2gKMjAyNjAzMDIsMjAyNi0wMy0wMiwyMDI2LDEsMyxNYXJjaAoyMDI2MDMwMywyMDI2LTAzLTAzLDIwMjYsMSwzLE1hcmNoCjIwMjYwMzA0LDIwMjYtMDMtMDQsMjAyNiwxLDMsTWFyY2gKMjAyNjAzMDUsMjAyNi0wMy0wNSwyMDI2LDEsMyxNYXJjaAoyMDI2MDMwNiwyMDI2LTAzLTA2LDIwMjYsMSwzLE1hcmNoCjIwMjYwMzA3LDIwMjYtMDMtMDcsMjAyNiwxLDMsTWFyY2gKMjAyNjAzMDgsMjAyNi0wMy0wOCwyMDI2LDEsMyxNYXJjaAoyMDI2MDMwOSwyMDI2LTAzLTA5LDIwMjYsMSwzLE1hcmNoCjIwMjYwMzEwLDIwMjYtMDMtMTAsMjAyNiwxLDMsTWFyY2gKMjAyNjAzMTEsMjAyNi0wMy0xMSwyMDI2LDEsMyxNYXJjaAoyMDI2MDMxMiwyMDI2LTAzLTEyLDIwMjYsMSwzLE1hcmNoCjIwMjYwMzEzLDIwMjYtMDMtMTMsMjAyNiwxLDMsTWFyY2gKMjAyNjAzMTQsMjAyNi0wMy0xNCwyMDI2LDEsMyxNYXJjaAoyMDI2MDMxNSwyMDI2LTAzLTE1LDIwMjYsMSwzLE1hcmNoCjIwMjYwNDAxLDIwMjYtMDQtMDEsMjAyNiwyLDQsQXByaWwKMjAyNjA0MDIsMjAyNi0wNC0wMiwyMDI2LDIsNCxBcHJpbAoyMDI2MDQwMywyMDI2LTA0LTAzLDIwMjYsMiw0LEFwcmlsCjIwMjYwNDA0LDIwMjYtMDQtMDQsMjAyNiwyLDQsQXByaWwKMjAyNjA0MDUsMjAyNi0wNC0wNSwyMDI2LDIsNCxBcHJpbAoyMDI2MDQwNiwyMDI2LTA0LTA2LDIwMjYsMiw0LEFwcmlsCjIwMjYwNDA3LDIwMjYtMDQtMDcsMjAyNiwyLDQsQXByaWwKMjAyNjA0MDgsMjAyNi0wNC0wOCwyMDI2LDIsNCxBcHJpbAoyMDI2MDQwOSwyMDI2LTA0LTA5LDIwMjYsMiw0LEFwcmlsCjIwMjYwNDEwLDIwMjYtMDQtMTAsMjAyNiwyLDQsQXByaWwKMjAyNjA0MTEsMjAyNi0wNC0xMSwyMDI2LDIsNCxBcHJpbAoyMDI2MDQxMiwyMDI2LTA0LTEyLDIwMjYsMiw0LEFwcmlsCjIwMjYwNDEzLDIwMjYtMDQtMTMsMjAyNiwyLDQsQXByaWwKMjAyNjA0MTQsMjAyNi0wNC0xNCwyMDI2LDIsNCxBcHJpbAoyMDI2MDQxNSwyMDI2LTA0LTE1LDIwMjYsMiw0LEFwcmlsCjIwMjYwNTAxLDIwMjYtMDUtMDEsMjAyNiwyLDUsTWF5CjIwMjYwNTAyLDIwMjYtMDUtMDIsMjAyNiwyLDUsTWF5CjIwMjYwNTAzLDIwMjYtMDUtMDMsMjAyNiwyLDUsTWF5CjIwMjYwNTA0LDIwMjYtMDUtMDQsMjAyNiwyLDUsTWF5CjIwMjYwNTA1LDIwMjYtMDUtMDUsMjAyNiwyLDUsTWF5CjIwMjYwNTA2LDIwMjYtMDUtMDYsMjAyNiwyLDUsTWF5CjIwMjYwNTA3LDIwMjYtMDUtMDcsMjAyNiwyLDUsTWF5CjIwMjYwNTA4LDIwMjYtMDUtMDgsMjAyNiwyLDUsTWF5CjIwMjYwNTA5LDIwMjYtMDUtMDksMjAyNiwyLDUsTWF5CjIwMjYwNTEwLDIwMjYtMDUtMTAsMjAyNiwyLDUsTWF5CjIwMjYwNTExLDIwMjYtMDUtMTEsMjAyNiwyLDUsTWF5CjIwMjYwNTEyLDIwMjYtMDUtMTIsMjAyNiwyLDUsTWF5CjIwMjYwNTEzLDIwMjYtMDUtMTMsMjAyNiwyLDUsTWF5CjIwMjYwNTE0LDIwMjYtMDUtMTQsMjAyNiwyLDUsTWF5CjIwMjYwNTE1LDIwMjYtMDUtMTUsMjAyNiwyLDUsTWF5CjIwMjYwNTIwLDIwMjYtMDUtMjAsMjAyNiwyLDUsTWF5CjIwMjYwNjAxLDIwMjYtMDYtMDEsMjAyNiwyLDYsSnVuZQoyMDI2MDYwMiwyMDI2LTA2LTAyLDIwMjYsMiw2LEp1bmUKMjAyNjA2MDMsMjAyNi0wNi0wMywyMDI2LDIsNixKdW5lCjIwMjYwNjA0LDIwMjYtMDYtMDQsMjAyNiwyLDYsSnVuZQoyMDI2MDYwNSwyMDI2LTA2LTA1LDIwMjYsMiw2LEp1bmUKMjAyNjA2MDYsMjAyNi0wNi0wNiwyMDI2LDIsNixKdW5lCjIwMjYwNjA3LDIwMjYtMDYtMDcsMjAyNiwyLDYsSnVuZQoyMDI2MDYwOCwyMDI2LTA2LTA4LDIwMjYsMiw2LEp1bmUKMjAyNjA2MDksMjAyNi0wNi0wOSwyMDI2LDIsNixKdW5lCjIwMjYwNjEwLDIwMjYtMDYtMTAsMjAyNiwyLDYsSnVuZQoyMDI2MDYxMSwyMDI2LTA2LTExLDIwMjYsMiw2LEp1bmUKMjAyNjA2MTIsMjAyNi0wNi0xMiwyMDI2LDIsNixKdW5lCjIwMjYwNjEzLDIwMjYtMDYtMTMsMjAyNiwyLDYsSnVuZQoyMDI2MDYxNCwyMDI2LTA2LTE0LDIwMjYsMiw2LEp1bmUKMjAyNjA2MTUsMjAyNi0wNi0xNSwyMDI2LDIsNixKdW5lCjIwMjYwNzAxLDIwMjYtMDctMDEsMjAyNiwzLDcsSnVseQoyMDI2MDcwMiwyMDI2LTA3LTAyLDIwMjYsMyw3LEp1bHkKMjAyNjA3MDMsMjAyNi0wNy0wMywyMDI2LDMsNyxKdWx5CjIwMjYwNzA0LDIwMjYtMDctMDQsMjAyNiwzLDcsSnVseQoyMDI2MDcwNSwyMDI2LTA3LTA1LDIwMjYsMyw3LEp1bHkKMjAyNjA3MDYsMjAyNi0wNy0wNiwyMDI2LDMsNyxKdWx5CjIwMjYwNzA3LDIwMjYtMDctMDcsMjAyNiwzLDcsSnVseQoyMDI2MDcwOCwyMDI2LTA3LTA4LDIwMjYsMyw3LEp1bHkKMjAyNjA3MDksMjAyNi0wNy0wOSwyMDI2LDMsNyxKdWx5CjIwMjYwNzEwLDIwMjYtMDctMTAsMjAyNiwzLDcsSnVseQoyMDI2MDcxMSwyMDI2LTA3LTExLDIwMjYsMyw3LEp1bHkKMjAyNjA3MTIsMjAyNi0wNy0xMiwyMDI2LDMsNyxKdWx5CjIwMjYwNzEzLDIwMjYtMDctMTMsMjAyNiwzLDcsSnVseQoyMDI2MDcxNCwyMDI2LTA3LTE0LDIwMjYsMyw3LEp1bHkKMjAyNjA3MTUsMjAyNi0wNy0xNSwyMDI2LDMsNyxKdWx5CjIwMjYwODAxLDIwMjYtMDgtMDEsMjAyNiwzLDgsQXVndXN0CjIwMjYwODAyLDIwMjYtMDgtMDIsMjAyNiwzLDgsQXVndXN0CjIwMjYwODAzLDIwMjYtMDgtMDMsMjAyNiwzLDgsQXVndXN0CjIwMjYwODA0LDIwMjYtMDgtMDQsMjAyNiwzLDgsQXVndXN0CjIwMjYwODA1LDIwMjYtMDgtMDUsMjAyNiwzLDgsQXVndXN0CjIwMjYwODA2LDIwMjYtMDgtMDYsMjAyNiwzLDgsQXVndXN0CjIwMjYwODA3LDIwMjYtMDgtMDcsMjAyNiwzLDgsQXVndXN0CjIwMjYwODA4LDIwMjYtMDgtMDgsMjAyNiwzLDgsQXVndXN0CjIwMjYwODA5LDIwMjYtMDgtMDksMjAyNiwzLDgsQXVndXN0CjIwMjYwODEwLDIwMjYtMDgtMTAsMjAyNiwzLDgsQXVndXN0CjIwMjYwODExLDIwMjYtMDgtMTEsMjAyNiwzLDgsQXVndXN0CjIwMjYwODEyLDIwMjYtMDgtMTIsMjAyNiwzLDgsQXVndXN0CjIwMjYwODEzLDIwMjYtMDgtMTMsMjAyNiwzLDgsQXVndXN0CjIwMjYwODE0LDIwMjYtMDgtMTQsMjAyNiwzLDgsQXVndXN0CjIwMjYwODE1LDIwMjYtMDgtMTUsMjAyNiwzLDgsQXVndXN0CjIwMjYwODIwLDIwMjYtMDgtMjAsMjAyNiwzLDgsQXVndXN0Cg==", BinaryEncoding.Base64),
			    Raw = Csv.Document(Binary, [Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Raw, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Headers, {"date_key", "calendar_date", "year", "month_name"}),
			    Typed = Table.TransformColumnTypes(Selected, {{"date_key", Int64.Type}, {"calendar_date", type date}, {"year", Int64.Type}, {"month_name", type text}}, "en-AU")
			in
			    Typed

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
