table QualityCheck
	lineageTag: 8124dd16-2847-5e52-a285-3aeec6460ca4

	measure 'Quality Check Count' = COUNTROWS(QualityCheck)
		formatString: #,0
		lineageTag: c835ac5f-f441-5980-ac01-99bc0c3027de

	measure 'Warning Check Count' = CALCULATE([Quality Check Count], QualityCheck[status] = "warn")
		formatString: #,0
		lineageTag: 98a915d1-27d0-54a9-8d8d-488a7e7e4538

	measure 'Failed Check Count' = COALESCE(CALCULATE([Quality Check Count], QualityCheck[status] = "fail"), 0)
		formatString: #,0
		lineageTag: 48d1f0c6-fa61-5f52-aa30-3b62c9d82a09

	measure 'Blocking Failure Count' = COALESCE(CALCULATE([Quality Check Count], QualityCheck[status] = "fail", QualityCheck[severity] = "critical"), 0)
		formatString: #,0
		lineageTag: ac822739-b098-5991-afc3-428170fb760d

	column quality_check_key
		dataType: string
		lineageTag: dff80809-84b0-5b72-bae7-2498a82ae44b
		summarizeBy: none
		sourceColumn: quality_check_key

		annotation SummarizationSetBy = Automatic

	column source_key
		dataType: string
		lineageTag: 50834b07-8575-5759-888c-1ba900a03073
		summarizeBy: none
		sourceColumn: source_key

		annotation SummarizationSetBy = Automatic

	column profiled_at_utc
		dataType: string
		lineageTag: 5698fc56-ccb0-5252-8877-c8cc503d6cc1
		summarizeBy: none
		sourceColumn: profiled_at_utc

		annotation SummarizationSetBy = Automatic

	column quality_dimension
		dataType: string
		lineageTag: 53be1db5-1c8e-5b2e-8027-b26895821940
		summarizeBy: none
		sourceColumn: quality_dimension

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 29221e8a-fb1b-58a4-8187-5fe3cef053ca
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column severity
		dataType: string
		lineageTag: 39aea0ec-2c62-5818-8bb7-c84adcdd90af
		summarizeBy: none
		sourceColumn: severity

		annotation SummarizationSetBy = Automatic

	column rows_evaluated
		dataType: int64
		formatString: 0
		lineageTag: 8dd417a6-5ecb-5f77-bc9c-be917d642ca2
		summarizeBy: none
		sourceColumn: rows_evaluated

		annotation SummarizationSetBy = Automatic

	column failed_rows
		dataType: int64
		formatString: 0
		lineageTag: 207f046a-1e84-511a-ad02-943ac374a5db
		summarizeBy: none
		sourceColumn: failed_rows

		annotation SummarizationSetBy = Automatic

	column failure_rate
		dataType: double
		lineageTag: 66de4c4e-7aad-530d-97f9-5e2db6b2f2ae
		summarizeBy: none
		sourceColumn: failure_rate

		annotation SummarizationSetBy = Automatic

	column detail
		dataType: string
		lineageTag: 5bda66df-e04b-598c-9c46-9d2368e41886
		summarizeBy: none
		sourceColumn: detail

		annotation SummarizationSetBy = Automatic

	partition QualityCheck-35361a66-0cec-5403-a2da-167809ea780c = m
		mode: import
		source =
			let
			    Binary = Binary.FromText("cXVhbGl0eV9jaGVja19rZXksc291cmNlX2tleSxwcm9maWxlZF9hdF91dGMscXVhbGl0eV9kaW1lbnNpb24sc3RhdHVzLHNldmVyaXR5LHJvd3NfZXZhbHVhdGVkLGZhaWxlZF9yb3dzLGZhaWx1cmVfcmF0ZSxkZXRhaWwKZDEtc25hcHNob3QtaGFzaCxEMSwyMDI2LTA5LTA5VDEzOjA3OjIzLjYxMTQ5NyswMDowMCxpbnRlZ3JpdHkscGFzcyxjcml0aWNhbCwxLDAsMC4wLFJhdyBzbmFwc2hvdCBleGlzdHMgYW5kIGl0cyBTSEEtMjU2IG1hdGNoZXMgdGhlIHNvdXJjZSBtYW5pZmVzdC4KZDEtcmVjb3JkLWNvdW50LEQxLDIwMjYtMDktMDlUMTM6MDc6MjMuNjExNDk3KzAwOjAwLHZvbHVtZSxwYXNzLGhpZ2gsMSwwLDAuMCxPYnNlcnZlZCA3MjcgZmVhdHVyZXM7IG1hbmlmZXN0IGRlY2xhcmVzIDcyNy4KZDEtYnVzaW5lc3Mta2V5LWNvbXBsZXRlLEQxLDIwMjYtMDktMDlUMTM6MDc6MjMuNjExNDk3KzAwOjAwLGNvbXBsZXRlbmVzcyxwYXNzLGNyaXRpY2FsLDcyNywwLDAuMCwiRXZlcnkgZmVhdHVyZSBoYXMgR2xvYmFsSUQsIE9CSkVDVElEIG9yIGZlYXR1cmUgaWQgZm9yIGFuIGFzc2V0IGJ1c2luZXNzIGtleS4iCmQxLWJ1c2luZXNzLWtleS11bmlxdWUsRDEsMjAyNi0wOS0wOVQxMzowNzoyMy42MTE0OTcrMDA6MDAsdW5pcXVlbmVzcyxwYXNzLGNyaXRpY2FsLDcyNywwLDAuMCxQcmVmZXJyZWQgR2xvYmFsSUQvZmFsbGJhY2sgT0JKRUNUSUQgYXNzZXQga2V5cyBhcmUgdW5pcXVlIGFmdGVyIGNhc2Ugbm9ybWFsaXphdGlvbi4KZDEtZ2VvbWV0cnktdmFsaWQsRDEsMjAyNi0wOS0wOVQxMzowNzoyMy42MTE0OTcrMDA6MDAsdmFsaWRpdHkscGFzcyxjcml0aWNhbCw3MjcsMCwwLjAsRXZlcnkgZmVhdHVyZSBpcyBhIFBvaW50IHdpdGggdmFsaWQgRVBTRzo0MzI2IGxvbmdpdHVkZSBhbmQgbGF0aXR1ZGUgcmFuZ2VzLgpkMS1kZXNjcmlwdGlvbi1wcmVzZW50LEQxLDIwMjYtMDktMDlUMTM6MDc6MjMuNjExNDk3KzAwOjAwLGNvbXBsZXRlbmVzcyx3YXJuLGxvdyw3MjcsMiwwLjAwMjc1MTAzMTYzNjg2MzgyNCxEZXNjcmlwdGlvbiBpcyBvcHRpb25hbCBjb250ZXh0OyBtaXNzaW5nIHZhbHVlcyBhcmUgcmV0YWluZWQgYXMgbnVsbC4KZDItc25hcHNob3QtaGFzaCxEMiwyMDI2LTA5LTA5VDEzOjA3OjIzLjYxMTQ5NyswMDowMCxpbnRlZ3JpdHkscGFzcyxjcml0aWNhbCwxLDAsMC4wLFJhdyBzbmFwc2hvdCBleGlzdHMgYW5kIGl0cyBTSEEtMjU2IG1hdGNoZXMgdGhlIHNvdXJjZSBtYW5pZmVzdC4KZDItY29sdW1uLXNoYXBlLEQyLDIwMjYtMDktMDlUMTM6MDc6MjMuNjExNDk3KzAwOjAwLHNoYXBlLHBhc3MsY3JpdGljYWwsMSwwLDAuMCxPYnNlcnZlZCBjb2x1bW5zIG1hdGNoIHRoZSA4IG1hbmlmZXN0IGZpZWxkcyBpbiBvcmRlci4KZDItcmVjb3JkLWNvdW50LEQyLDIwMjYtMDktMDlUMTM6MDc6MjMuNjExNDk3KzAwOjAwLHZvbHVtZSxwYXNzLGhpZ2gsMSwwLDAuMCxPYnNlcnZlZCAyNDE5NyByb3dzOyBtYW5pZmVzdCBkZWNsYXJlcyAyNDE5Ny4KZDItcmVxdWlyZWQtY29tcGxldGVuZXNzLEQyLDIwMjYtMDktMDlUMTM6MDc6MjMuNjExNDk3KzAwOjAwLGNvbXBsZXRlbmVzcyxwYXNzLGhpZ2gsMjQxOTcsMCwwLjAsQWxsIGVpZ2h0IHNvdXJjZSBmaWVsZHMgYXJlIG5vbi1ibGFuayBwZXIgYWdncmVnYXRlIHJvdy4KZDItdHlwZS12YWxpZGl0eSxEMiwyMDI2LTA5LTA5VDEzOjA3OjIzLjYxMTQ5NyswMDowMCx2YWxpZGl0eSxwYXNzLGNyaXRpY2FsLDI0MTk3LDAsMC4wLCJEYXRlIHBhcnNlcyBhcyBERC9NTS9ZWVlZIGFuZCBZZWFyLCBNb250aCBhbmQgUmVxdWVzdCBDb3VudCBwYXJzZSBhcyBpbnRlZ2Vycy4iCmQyLXBlcmlvZC1jb25zaXN0ZW5jeSxEMiwyMDI2LTA5LTA5VDEzOjA3OjIzLjYxMTQ5NyswMDowMCxjb25zaXN0ZW5jeSxwYXNzLGhpZ2gsMjQxOTcsMCwwLjAsRGF0ZSBpcyB0aGUgZmlyc3QgZGF5IG9mIHRoZSBZZWFyL01vbnRoIHN1cHBsaWVkIG9uIHRoZSBzYW1lIHJvdy4KZDItY291bnQtbm9ubmVnYXRpdmUsRDIsMjAyNi0wOS0wOVQxMzowNzoyMy42MTE0OTcrMDA6MDAsdmFsaWRpdHkscGFzcyxjcml0aWNhbCwyNDE5NywwLDAuMCxQdWJsaXNoZWQgYWdncmVnYXRlIHJlcXVlc3QgY291bnRzIGFyZSBub24tbmVnYXRpdmUgaW50ZWdlcnMuCmQyLWV4YWN0LXJvdy11bmlxdWUsRDIsMjAyNi0wOS0wOVQxMzowNzoyMy42MTE0OTcrMDA6MDAsdW5pcXVlbmVzcyxwYXNzLGhpZ2gsMjQxOTcsMCwwLjAsTm8gZHVwbGljYXRlIGZ1bGwgc291cmNlIHJvd3MgYWZ0ZXIgdHJpbW1pbmcgd2hpdGVzcGFjZS4KZDItbm9ybWFsaXplZC1rZXktY29sbGlzaW9uLEQyLDIwMjYtMDktMDlUMTM6MDc6MjMuNjExNDk3KzAwOjAwLHVuaXF1ZW5lc3Msd2FybixtZWRpdW0sMjQxOTcsMSw0LjEzMjc0MzcyODU2MTM5MmUtMDUsQ291bnRzIHB1Ymxpc2hlciByb3dzIHRoYXQgY29sbGlkZSBvbiBjYXNlLW5vcm1hbGl6ZWQgR3JvdXAgQ29kZSArIENhdGVnb3J5IENvZGUgKyBEYXRlLiBSb3dzIHJlbWFpbiBzZXBhcmF0ZSBhbmQgYXJlIG5ldmVyIHNpbGVudGx5IG1lcmdlZDsgZG93bnN0cmVhbSBmYWN0cyB1c2UgYSBkZXRlcm1pbmlzdGljIGZ1bGwtcm93IGtleSBhbmQgcmV0YWluIHRoZSByYXcgY29kZXMuCmQyLW5vLWZ1dHVyZS1wZXJpb2QsRDIsMjAyNi0wOS0wOVQxMzowNzoyMy42MTE0OTcrMDA6MDAsdGltZWxpbmVzcyxwYXNzLGhpZ2gsMjQxOTcsMCwwLjAsTm8gc291cmNlIHBlcmlvZCBpcyBsYXRlciB0aGFuIHRoZSByZXRyaWV2YWwgZGF0ZS4KZDItbW9udGhseS1mcmVzaG5lc3MsRDIsMjAyNi0wOS0wOVQxMzowNzoyMy42MTE0OTcrMDA6MDAsdGltZWxpbmVzcyxwYXNzLG1lZGl1bSwxLDAsMC4wLExhdGVzdCBwZXJpb2QgZW5kcyAyMDI2LTA3LTMxOyByZXRyaWV2YWwgbGFnIGlzIDQwIGRheXMgKHdhcm4gYWJvdmUgNjIpLgpkMi1ncm91cC1sYWJlbC1zdGFiaWxpdHksRDIsMjAyNi0wOS0wOVQxMzowNzoyMy42MTE0OTcrMDA6MDAsY29uc2lzdGVuY3ksd2Fybixsb3csOTgsMiwwLjAyMDQwODE2MzI2NTMwNjEyLENvdW50cyBub3JtYWxpemVkIGdyb3VwIGNvZGVzIHRoYXQgbWFwIHRvIG1vcmUgdGhhbiBvbmUgZGVzY3JpcHRpb24gYWNyb3NzIGhpc3RvcnkuCmQyLWNhdGVnb3J5LWxhYmVsLXN0YWJpbGl0eSxEMiwyMDI2LTA5LTA5VDEzOjA3OjIzLjYxMTQ5NyswMDowMCxjb25zaXN0ZW5jeSx3YXJuLGxvdyw0MTgsMzUsMC4wODM3MzIwNTc0MTYyNjc5NSxDb3VudHMgbm9ybWFsaXplZCBjYXRlZ29yeSBjb2RlcyB0aGF0IG1hcCB0byBtb3JlIHRoYW4gb25lIGRlc2NyaXB0aW9uIGFjcm9zcyBoaXN0b3J5Lgo=", BinaryEncoding.Base64),
			    Raw = Csv.Document(Binary, [Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Raw, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Headers, {"quality_check_key", "source_key", "profiled_at_utc", "quality_dimension", "status", "severity", "rows_evaluated", "failed_rows", "failure_rate", "detail"}),
			    Typed = Table.TransformColumnTypes(Selected, {{"quality_check_key", type text}, {"source_key", type text}, {"profiled_at_utc", type text}, {"quality_dimension", type text}, {"status", type text}, {"severity", type text}, {"rows_evaluated", Int64.Type}, {"failed_rows", Int64.Type}, {"failure_rate", type number}, {"detail", type text}}, "en-AU")
			in
			    Typed

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
