table Review
	lineageTag: 5e1b20bc-2ed1-5b75-ab56-fcea102e88a3

	measure 'Review Count' = COUNTROWS(Review)
		formatString: #,0
		lineageTag: 14c30d36-9b4a-52ba-9931-4728704f2f36

	measure 'Median Review Lag' = MEDIAN(Review[review_lag_minutes])
		formatString: #,0 "min"
		lineageTag: b1fae483-d601-5981-b418-ac70d09bd02a

	column decision_key
		dataType: string
		lineageTag: cad87dad-dad2-582c-983a-faa11d8e2dcf
		summarizeBy: none
		sourceColumn: decision_key

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 8da073ce-9187-5e6b-bfc8-27107a0ad7a7
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column review_action
		dataType: string
		lineageTag: 89b174d3-4e3c-588c-9df5-c25c644e6efd
		summarizeBy: none
		sourceColumn: review_action

		annotation SummarizationSetBy = Automatic

	column review_lag_minutes
		dataType: double
		lineageTag: b16992cc-36b0-561e-a8cc-ccab2c7df1bb
		summarizeBy: none
		sourceColumn: review_lag_minutes

		annotation SummarizationSetBy = Automatic

	column data_truth_class
		dataType: string
		lineageTag: 192658ce-dd32-5568-9f53-094c7f9707c7
		summarizeBy: none
		sourceColumn: data_truth_class

		annotation SummarizationSetBy = Automatic

	partition Review-53a7b910-7d08-5767-87c2-6319ad465ebb = m
		mode: import
		source =
			let
			    Binary = Binary.FromText("cmV2aWV3X2tleSxkZWNpc2lvbl9rZXksZGF0ZV9rZXksb2NjdXJyZWRfYXRfdXRjLHJldmlld2VyX2lkLHJldmlld19hY3Rpb24scmV2aWV3X2xhZ19taW51dGVzLGNvcnJlY3RlZF9jYXRlZ29yeSxjb3JyZWN0ZWRfcHJpb3JpdHkscmVwbGFjZW1lbnRfYWN0aW9uLGRhdGFfdHJ1dGhfY2xhc3MKOTI0NDljNTUtY2EwZi01OTgwLTg4NDItYzhmZjc3MjU2ODRjLDllNDNlZmFiLTA0NzUtNTU0MS05NmM0LWRkZTc5ODQxMzc5YywyMDI1MDkwMSwyMDI1LTA5LTAxVDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjEsb3ZlcnJpZGUsMjQwLjAsLFAyLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKNWFhMGM4YWItNTY3NS01YmIzLTg2YTUtMWY4ZmMzOGFiY2YwLDIyMjkwMTA0LTE2YTgtNTg5MS1iODAyLTI0ZTFiNjM0OGUxYywyMDI1MDkwMiwyMDI1LTA5LTAyVDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsYWNjZXB0LDMwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAplZTg1MzZlOC02Nzk2LTViMmMtOGI4MS1hMDc3YWZhOGVmMTgsNjY5NTg5ZmEtMmIwZC01M2I5LWE1ZmMtY2JmNTZmZDJmYTdjLDIwMjUwOTA0LDIwMjUtMDktMDRUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSw0MjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKMjk3MjFiZjQtODkyOC01ZDNiLTg2NTYtYmYwZjRiZjFhNzQyLDc4NDVkNjliLWZhM2YtNWFhYi05NGFmLTc2Mzg5Yjk2MDQ3ZiwyMDI1MDkwNSwyMDI1LTA5LTA1VDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsZXNjYWxhdGUsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmY5MDZmZTA5LTE3NTgtNTlmMS1iNDJjLWRlMWEyOTQwMjJhNixiNzI1ZWNmOC00MTMzLTU5ZmItOGZlNC1lZDExMjMwNmRlNDQsMjAyNTA5MDcsMjAyNS0wOS0wN1QxOTowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDYwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAozYmY1ZTZmMS1lYmFhLTU1YTQtYjExNi00ZDhjMDZjNzRlNmYsOTExOGVlYzktMGEzZS01YjFhLTgzNDQtY2JlZDgwOGU0OTVkLDIwMjUwOTA4LDIwMjUtMDktMDhUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxhY2NlcHQsNjYwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjFmN2IzMTUyLWRiOGEtNWRjOC1hYTNjLWVmNWFjMGM2NWVhMyw1NjA1MDQzNy01ZWRjLTUxNTAtODU4OS04YTE5YjQ3YzUwOTEsMjAyNTA5MTAsMjAyNS0wOS0xMFQxMzowMDowMCswMDowMCxyZXZpZXdlcjoyLG92ZXJyaWRlLDI0MC4wLHdhc3RlX2xpdHRlciwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAplOTk4YzQwNC0zZWFiLTU5OGEtOGQ1Ny04ODA0ODVjZTk0MjMsYzI1MTFmODItY2Q5Yi01NGQzLWIwZTMtNmU0Y2FlM2E0ZDUzLDIwMjUwOTExLDIwMjUtMDktMTFUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6MyxhY2NlcHQsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmQyMGIyYzY1LTVjODYtNWJkNS05Zjc4LTFjMDY5YzhhMzNkOCwwN2QxNTgzOC1kNzBlLTVjYTMtYjZhYy01MzRkNzI3MTZhNDcsMjAyNTA5MTMsMjAyNS0wOS0xM1QxNjowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAplY2I3NDUyZi00NDlkLTVkNTAtYmU2Zi00MmYzZjQ1ZDgxMTAsMjY0NTIwYjQtYmJkMy01MDMyLTk1OTQtZTU2Y2MxMzJlYWNmLDIwMjUwOTE0LDIwMjUtMDktMTRUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSw0ODAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKN2YwMmZhYzYtMzEyYy01MzEyLWJlMjgtMTIyMWRlNzVmYWRlLDM2YjFhMjc2LWM5OGUtNTg5MS1iNzMxLTk4ZjYzOGFhNGQ4MiwyMDI1MTAwMSwyMDI1LTEwLTAxVDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjZlOTI1MTIxLTA3NDAtNTIzOS1hYTQ4LTc2Yzg1YWM0Njc4MCwwYTBmZTUzYS00YTBiLTU2MWUtOWQ3NS00MzkxODIzNzY2YjUsMjAyNTEwMDIsMjAyNS0xMC0wMlQyMDowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAoxYWQ4NzdjNS1jOWZkLTViNDktOTNjMi03YjIxNWUzZTUzNzEsZGQxOWViNWItNTE5NS01OWIwLWE0NDUtMGUwMjA3ZGY4YjM2LDIwMjUxMDA0LDIwMjUtMTAtMDRUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6MyxhY2NlcHQsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmM3YzliZDc4LWZkZjEtNWI5NC1iNDY2LTE0NjJkMmY5YTAwYixlYjhjOGIxZi03N2Y2LTU0NWMtOTMzOS04NjQzZGIxMTZjY2EsMjAyNTEwMDUsMjAyNS0xMC0wNVQxNDowMDowMCswMDowMCxyZXZpZXdlcjo0LGVzY2FsYXRlLDMwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAoxOGZjYzM2MS05NWVlLTVjODAtYmM2ZS05NTE2MTg5M2ExYzksYmQ1OGNmNjQtMjkzOC01ODJmLTg3YTMtODBmODhkMDhlMTQxLDIwMjUxMDA3LDIwMjUtMTAtMDdUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixhY2NlcHQsNDIwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmYzN2EyODE4LTE5NjAtNTM3NS04YzJiLWI4MmM2OGQyOTcxNywyNzMyN2E5Mi1hNWFmLTVkMTEtYTA4Zi1hYTdmOTk0Y2Q5ODcsMjAyNTEwMDgsMjAyNS0xMC0wOFQxNzowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDQ4MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAphMmMyZDdlZC0wNDhmLTUzYTgtYWRkYi0zZjJmMmIxYTFjZjQsNDNmYzJjZDAtZjgyOC01Mzc4LWEzZWEtMjRlMzRjODk1NzgzLDIwMjUxMDEwLDIwMjUtMTAtMTBUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxlc2NhbGF0ZSw2MDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKMTk5NjVjYzktMzliYi01Y2YzLThjZTYtNGZjM2NiODQ3MjFiLDYwOTAzNDlhLWI2NGEtNTg0Mi05OWJiLTk1MmI2NzAxMTRjNCwyMDI1MTAxMSwyMDI1LTEwLTExVDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsNjYwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmMyNTg4NDY0LTc0ZGMtNTgxNS1iNDhkLWVlZDdiMGQ4ZTc3YiwzNzM1OGNhYi0yOWU0LTU1NWUtOWIwMy02ZDYyYWYzZDBhODUsMjAyNTEwMTMsMjAyNS0xMC0xM1QxMzowMDowMCswMDowMCxyZXZpZXdlcjo0LGFjY2VwdCwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKYjc4OTQxMmMtMzZjOC01NDdiLTg1ZDgtZjliNzVkMWY4ZTc1LGM5NjI0ZTMxLTY3ZjYtNTljZi1hODJjLTMxYWRiOTU5NzMxNiwyMDI1MTAxNCwyMDI1LTEwLTE0VDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsYWNjZXB0LDMwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo5ZTE5ZjU5Mi1lOTMwLTUyNmYtYmFmZi1hNjJiMGU0MWFlODksNmI4Zjk2NjgtNTZhMS01NjRjLWFkN2ItYzMzNDNkZTczM2FlLDIwMjUxMTAxLDIwMjUtMTEtMDFUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6MyxhY2NlcHQsNDIwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjYyNTMyMTRhLTVlMGYtNTNjYi04NDUyLWRhNGYyZGU4NjAyYSwyZDlmMjk5Ny05ZjViLTU1NDgtYjY4OS01YTAzZmNkMWY3MWYsMjAyNTExMDIsMjAyNS0xMS0wMlQxNzowMDowMCswMDowMCxyZXZpZXdlcjo0LGFjY2VwdCw0ODAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKYzJhYjczZjYtNzQyMi01MDUwLThhNTAtM2YwYzA4ZTk0NzIyLDY4YTlhOTRjLTBkZjMtNTc0YS1iY2E1LWE0YTlkMDVkM2M1YiwyMDI1MTEwNCwyMDI1LTExLTA0VDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsNjAwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmE5YWVjNWFhLTU1OGMtNWEyNC1iMjc2LTVhYjg0OGUxYWZjZSxkN2U1NWI1Yy05NTAxLTVjNDQtOGM4Zi1lYzE3YmZlYzY3ODAsMjAyNTExMDUsMjAyNS0xMS0wNVQyMDowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo1MTczZDkwOC1hMDIwLTU0YjEtOGQ4ZC05YThmY2IwMTFjMTUsZGMyMDdjYmYtYzEwMS01MjgzLTg2YmEtZWEwM2YxODYzMDVjLDIwMjUxMTA3LDIwMjUtMTEtMDdUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxlc2NhbGF0ZSwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKN2EzMzExN2YtOWQ0OS01OTc1LTkzYzItNjEwMTZhYTQwZDU2LGMyZDkxOGU1LTZjODAtNTI3YS1hNjc1LTI1NzJiMzMwOGNiZiwyMDI1MTEwOCwyMDI1LTExLTA4VDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsYWNjZXB0LDMwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAplYTQ0YmNiNy0zNDhhLTVmZDYtOTJiYS0xYjIyMzJhNDRiODgsYWUwY2UwZTgtNWE4Yy01ZmJlLWE0MjQtNDhlOTI4OTVjZDc3LDIwMjUxMTEwLDIwMjUtMTEtMTBUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSw0MjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKYzQyMjE3YTMtNmQxNC01N2E2LWFjNGItOWRkM2ZlYTUyNDVlLDkwMjY1Y2E3LTY5M2MtNTc1OC05MDkzLWVhMjIxMTQ4ZDE5MiwyMDI1MTExMSwyMDI1LTExLTExVDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsb3ZlcnJpZGUsNDgwLjAsLFAyLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKMGNmMWJkZDAtNGMyMC01MmU5LWFmMmQtOGM5M2FkMjkzNTFhLGU1MjRjYzg1LWViMjYtNTZkZi1iNDYxLTI4MjIxODI1MWUwOCwyMDI1MTExMywyMDI1LTExLTEzVDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjMsZXNjYWxhdGUsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjI1ZTk1Mzc0LThkODgtNWQ5ZC05NWI5LTNiNzkyMmEyNTg4NCw0NWI3NzZmMS00ZDcyLTU0ZTYtOTU5My1kNGEyMzBlMWE4YjAsMjAyNTExMTQsMjAyNS0xMS0xNFQyMDowMDowMCswMDowMCxyZXZpZXdlcjo0LGVzY2FsYXRlLDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo2YmYzZmEwYS1lM2IyLTU1NmYtOTQzNi0wZjZjMTJkNjJlYTUsYmZjN2JmMGItZGEzNS01ODFkLWJkOTAtZjFlMGQxNDBlMTNlLDIwMjUxMjAxLDIwMjUtMTItMDFUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSwyNDAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKM2EzOTI1ZDktMjgyMC01NWE0LTgxYzYtYjc4NTMwNmY1YTlkLDU2Mjg3YmU1LWZlMjYtNWNmNS1iYmU0LWFmMzA4MzUzYWQ4YiwyMDI1MTIwMiwyMDI1LTEyLTAyVDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjMsZXNjYWxhdGUsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjI3ZDdjZjQ3LWZhOTQtNTkyZS1iZjFhLTQ2MDdmZmZjMGU4NywyZDM1YmU0Ni1jZGE3LTU3ZTMtYmYzYS03ZTc1MDRiMjExMTksMjAyNTEyMDQsMjAyNS0xMi0wNFQxNjowMDowMCswMDowMCxyZXZpZXdlcjoxLG92ZXJyaWRlLDQyMC4wLCxQMiwsc3ludGhldGljX29wZXJhdGlvbmFsCmNlOWM4MDhkLTc0OWQtNWI5ZS04MjY4LTZiZTc1OTQ0MmIzNixkNzQ4YWNiOC0yMDFjLTU3YzItYTJmNi04MGFkN2U1OWE5NWYsMjAyNTEyMDUsMjAyNS0xMi0wNVQxNzowMDowMCswMDowMCxyZXZpZXdlcjoyLG92ZXJyaWRlLDQ4MC4wLHdhc3RlX2xpdHRlciwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApkYWEyNDI5Yi00Nzc3LTU0ODAtYmJmOS1jZTlmOWJjNTMzNTEsNDM5NTE1YzMtNzM3Mi01ZDM3LTgxYWEtZTE2NWVhYmQ1NzI1LDIwMjUxMjA3LDIwMjUtMTItMDdUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxhY2NlcHQsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjFlODFhMmE5LTA1NmEtNTgxMi05MjFmLWNiMTZmMjc5OTFlZiw5NWVkNDdmNC1mMDQ0LTVmNGUtOGU5NS0xNjBhN2Y3NDVhMDcsMjAyNTEyMDgsMjAyNS0xMi0wOFQyMDowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAplOWNkN2IyZC1hODJlLTU5OWItYmUzYy0zMmRhOGIzM2QyNTksNjNjODdiM2YtNWJlNC01NTk3LWE5ZjctZTQ5MmJjNTI5ZDI1LDIwMjUxMjEwLDIwMjUtMTItMTBUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6Myxlc2NhbGF0ZSwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKNjEzZTRiOTQtNjQyZS01Yzc5LWJmYTMtOTBhYzYzYjEzNGI5LDg3MTk1OGNiLWE4MjgtNWFhZi05M2ZlLWZiYmRiMmYwYTRhYiwyMDI1MTIxMSwyMDI1LTEyLTExVDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjQwYTBjMzllLTc2MGMtNWQ0My1hNWI5LTBiZjM5ZDc1ZGQ4OCw0ZWMyNGY0Mi04MTgwLTU4MmQtODUxMi04Y2E1YTdiZTgxOGUsMjAyNTEyMTMsMjAyNS0xMi0xM1QxNjowMDowMCswMDowMCxyZXZpZXdlcjoyLGFjY2VwdCw0MjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKMGIzNTE5MDQtYTkyZS01MzhkLTk3YzktZjllZDliN2VmNTA0LDhhMGMxNDI0LThlY2QtNWFjOC04MjAzLWU3OWEyM2VlZTJmZSwyMDI1MTIxNCwyMDI1LTEyLTE0VDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjMsYWNjZXB0LDQ4MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApmMmFhMmE5NS1hNTI2LTUxYjMtYTJlOS1lNGIwNGI3ODA0NGIsZjRjNWViZjgtM2Q3OS01YjFlLTg4MjMtNmQ5NWFiOWJiZjVkLDIwMjYwMTAxLDIwMjYtMDEtMDFUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxhY2NlcHQsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjEyNTQxMTZmLTg4N2YtNTI1ZC05NWZlLWYxODczOWYyOWVjYSwyNTlkZDdmZC0yZjY5LTU1NGItODU3Zi03MjMyMjZhMjM3ZmYsMjAyNjAxMDIsMjAyNi0wMS0wMlQyMDowMDowMCswMDowMCxyZXZpZXdlcjoyLGFjY2VwdCw2NjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKMDhmYzk4ZjYtZTc4Yi01MzcxLWEzOWUtMDdjMzJkNTM3ZmZiLGYyYTU3ZjUxLWFmMmEtNTI3NC04MzQ1LTBhOWQzMTNmYjQyYSwyMDI2MDEwNCwyMDI2LTAxLTA0VDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmY0YjI2ZTA1LTU0NjItNTdlYi05YjcwLWJhMjE4OWYxMmNlZSw2N2JiNmM4Yi0zN2IxLTViYzUtYjQyMy03NGI2MzEyNmRkZGQsMjAyNjAxMDUsMjAyNi0wMS0wNVQxNDowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDMwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApmZWY5MWY4Zi1mN2U2LTU5MGUtOTg2NS00M2JmNmQ5ZDQyZmQsZDRkMTllZWQtYjM5Ni01YTRjLTkxMjEtZWU1MjgwNWQ1NWMzLDIwMjYwMTA3LDIwMjYtMDEtMDdUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6Myxlc2NhbGF0ZSw0MjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKNGYxODEzMWItMTI4OC01ODU3LTlhYTktMDk4NmZkOTNlNjM4LDlhNjg4ZmY1LTk2M2MtNTFlOS04YTk2LWYyNTJiYzlhMGRjYSwyMDI2MDEwOCwyMDI2LTAxLTA4VDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsYWNjZXB0LDQ4MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApjZDEyODY0Zi0xZjQ0LTUwZTctODUwZC05ZjAwNTRkOThkOWMsNTkyN2I2Y2UtYTk1NC01Nzk4LTlkODQtMWY0ZTU5NDc0YTc0LDIwMjYwMTEwLDIwMjYtMDEtMTBUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSw2MDAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKNWQ0YWE3MmEtODQ0Zi01MTVhLTg0YjAtMjFjNmMwYWRmYmMzLDFmMDc4ZDkxLTE1MzEtNTY4OC04Yzg3LTBjOGIyNTQ1NmI4OCwyMDI2MDExMSwyMDI2LTAxLTExVDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjMsYWNjZXB0LDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo1ZGNiODZmZC00ZGZiLTUwNTctOTE2My1iODViMDI3ZTc2NTQsMGUyODA0ZTktZjc2Mi01MjQ4LWI1YjktNGYxZWUyM2Y3ODRkLDIwMjYwMTEzLDIwMjYtMDEtMTNUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxlc2NhbGF0ZSwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKMTgwN2Y0YmItMjk3NS01OTlhLThkNWEtOGE4YTUyNGY4ZjgzLDA5NzJmMDY4LTRjYTYtNWFmMi1iNzNmLTZlYTEzOTI0ZTI2NiwyMDI2MDExNCwyMDI2LTAxLTE0VDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsMzAwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjI3YTc3MjA5LTQ0MmYtNTRhMS1hZDk4LTFiOGViNmNmZjlmYywwMTEwMGFlMC1jMTA4LTU4NTItYjBkMC02MDQxNDk3ZmI0NGEsMjAyNjAyMDEsMjAyNi0wMi0wMVQxNjowMDowMCswMDowMCxyZXZpZXdlcjo0LGVzY2FsYXRlLDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApiMmY4N2QxMS1hZTA0LTVhZDUtODYwOC1jNjI2OTJjNmU0MGUsY2JjYzU5YzgtN2NlOC01NWYwLTg0OWEtZDRlODk0OTcyZTQwLDIwMjYwMjAyLDIwMjYtMDItMDJUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxlc2NhbGF0ZSw0ODAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKYzJkMmYyYzQtMGYwNS01YjM0LTgzY2UtMzFiYTk3MjU1NDU3LDZhYTFiNTZkLWZlNTktNWE5YS04MGExLTI1YTJiNjdkZWJhNywyMDI2MDIwNCwyMDI2LTAyLTA0VDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjMsYWNjZXB0LDYwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo0MzNmMWFkMC1lODViLTU3ZWEtYWJjMS1lOWY3NTJmZGExOWIsZmM5YzRlY2QtYzc4NS01NWM3LTliZDItN2M3ODZkYzhlODBjLDIwMjYwMjA1LDIwMjYtMDItMDVUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSw2NjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKMmJhYWZmYTQtYmNmNS01MWQ5LTgxY2UtZmY2N2M2ZGQxMzQzLDIzZjBmNDc4LWVlNGUtNWFiZC05ZTY5LTMxNjNkNmJiYTA5NCwyMDI2MDIwNywyMDI2LTAyLTA3VDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjIsYWNjZXB0LDI0MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo0M2Q4NGZlZS0xNDRhLTVjMTgtYjBlNS1lZjhkYmMwOTQ2NTQsODI1YTQxZTQtZjAwZC01MjliLThiMDQtNjQ4MTE2Y2NmZGYyLDIwMjYwMjA4LDIwMjYtMDItMDhUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6Myxlc2NhbGF0ZSwzMDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKYTAxZDJhZTctZGEwZS01ODQyLWJjYzctNzM2N2YzYjgyYmRlLGUxNjg0MWM2LWI4YzgtNWY2Mi05OWMxLTMwNWMzZmVjZjU0OSwyMDI2MDIxMCwyMDI2LTAyLTEwVDE2OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsZXNjYWxhdGUsNDIwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjU2MTk4ZjdkLWE0ODQtNTkwMy04NzgwLTg4MzAxMTQ3MmNhOCw3MjE4NzIxZS04ZjI3LTUyZGEtYTU4ZC04ZTk2OTgzYmM3ODUsMjAyNjAyMTEsMjAyNi0wMi0xMVQxNzowMDowMCswMDowMCxyZXZpZXdlcjoyLG92ZXJyaWRlLDQ4MC4wLHdhc3RlX2xpdHRlciwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApiODRmNTgyYy04MmZiLTUxNTUtYTc4OS1lMTdjYTY5MjQ3MGEsOTYxNTE2NTMtNzQ5Yi01OWFkLWI5Y2QtZWVlNTAxMDI3N2IwLDIwMjYwMjEzLDIwMjYtMDItMTNUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxhY2NlcHQsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjk0MDMwY2NhLTQ2MTEtNTkwOS1iNTc1LTM2ZDhmOWVlZWNiNSxlMmJmMDczYS1hZmFjLTVmYzItOTJhNS00MTZlMGQyNWUyZjMsMjAyNjAyMTQsMjAyNi0wMi0xNFQyMDowMDowMCswMDowMCxyZXZpZXdlcjoxLG92ZXJyaWRlLDY2MC4wLCxQMiwsc3ludGhldGljX29wZXJhdGlvbmFsCjIxMjg4NDkyLTU4MjYtNTBlMy1iMDNiLWM2NjU5NzM2YjU0MCw3YjM4MzY3OC03NWEzLTUwMDAtOTI1Yi00YmJhZGFjYWNiNTksMjAyNjAzMDEsMjAyNi0wMy0wMVQxMzowMDowMCswMDowMCxyZXZpZXdlcjozLGFjY2VwdCwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKYzZmYjlhYTEtNjE1NS01ODI0LWEwNDQtMWU5NTRiNTgzN2MzLGFjMDIxMWZkLTM4ZTUtNTc4Mi04MjFkLWU1ZTE0NmZmMWRhNywyMDI2MDMwMiwyMDI2LTAzLTAyVDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsYWNjZXB0LDMwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAowYTg0N2U4NC02NzY4LTUyNGItYmJmMC0xMzAyNGQ5OWM1ODksMzI3Mjg0MjAtOGVjMC01MmE2LWE1YzMtYWQyODJhZWJhYjcyLDIwMjYwMzA0LDIwMjYtMDMtMDRUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSw0MjAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKNGVmNWFmZjItZjFiMi01MGVkLTliNWMtMjRlMzI2ZGJhMGQyLDE3MTkxMmFlLTBlY2YtNTI0MS1hODYxLTY0YTg4YTg5OTQ5YSwyMDI2MDMwNSwyMDI2LTAzLTA1VDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjMsZXNjYWxhdGUsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmE3NmNhOGQ2LTM0OWItNWQ0ZS04MjBjLWE5MTMwZWViYjc3MCwzM2ZlZjY0Yy1hODFiLTViOGYtOTg1ZS02ZTYwYzQ5MzUxMTEsMjAyNjAzMDcsMjAyNi0wMy0wN1QxOTowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDYwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAozMWUxZjNmMy1kMzhmLTUxM2MtODM5My0yMTE4NDk5YTIwODIsN2RmMjZlM2YtZWQ5Yi01ZmJmLThhYjctYjE0YWRhZTFmYWFkLDIwMjYwMzA4LDIwMjYtMDMtMDhUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixhY2NlcHQsNjYwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjkyM2UzY2RjLTkxOTAtNWJkOC04ZjNmLTc5MzU5ZjQ5MDU3MCwzMjM0NjQzMi1mZGI0LTVjMWUtYmRjYy03Mzg1MGIxNDMyZTgsMjAyNjAzMTAsMjAyNi0wMy0xMFQxMzowMDowMCswMDowMCxyZXZpZXdlcjo0LGVzY2FsYXRlLDI0MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo1ZjQ0MzVjYi0zZTU5LTUwMDctOGIyMi1iZGJmMDFhYjM4YzAsYzFlY2U5YTEtODU2Zi01OTkzLWFlZDMtMmU5MzBlZjVlNjdhLDIwMjYwMzExLDIwMjYtMDMtMTFUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxhY2NlcHQsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmRmYmZlZGVmLTljYzQtNTExNi05YTYyLTdkMDA5OTIwNmEwZSw4NGFhYTVhOC1lZWE3LTU4NzItODYwNi1kZDg1YWIyYWY5M2IsMjAyNjAzMTMsMjAyNi0wMy0xM1QxNjowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo0N2M2NTNkYy1kYjJjLTVmNDMtODQ5Ni03YzE0YTBhZDcyOWYsNzQzN2VlOTktN2VjMC01ZmU0LWJiNTYtM2Y4OTVhOGY3ZWQ5LDIwMjYwMzE0LDIwMjYtMDMtMTRUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSw0ODAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKYWQxNzRjN2EtNTlkNi01MmI0LWJmOGQtOGMyYWJlNTg2YjZkLGI4YTk4NjM5LTJjZDItNTZiMS04NzhiLWQ3ZjQ1NjQ2NzkzMCwyMDI2MDQwMSwyMDI2LTA0LTAxVDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsNjAwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjFmZTUzNDI5LThjOTgtNTBlOC1hYTJmLTQ2NDYzNTFjNWVhNiw3ZjY0MmRiYi01ZjQxLTUyYTMtYTA4Ni0yNjdjZTZjMjRhODksMjAyNjA0MDIsMjAyNi0wNC0wMlQyMDowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAphZGFhOTllNS00OWVjLTViNDYtODI4YS1mNTkzOTI1YThiZmIsMjI2MjVhYjMtYjcxMi01Y2Q3LWFhNmItMTEyNDY4MzJkMDQzLDIwMjYwNDA0LDIwMjYtMDQtMDRUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxhY2NlcHQsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjMzZDgyY2Y4LTE0ODUtNTc2Mi1iMDdhLWYwNTIzOWZhNWU4ZixkZTg3NzBiZS1kOTIyLTU2NTQtYjMyZS1lY2Q5NTlmY2Y4NGUsMjAyNjA0MDUsMjAyNi0wNC0wNVQxNDowMDowMCswMDowMCxyZXZpZXdlcjoyLG92ZXJyaWRlLDMwMC4wLHdhc3RlX2xpdHRlciwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApkZDA5Yjk4MC01OWFhLTVjZmQtOTBhYi1hYzQzYzAzMjRkMjQsZDYyODA0OGQtZDNhOS01ZDlmLTlhZDUtOTM4ZGE1MTU4MTg1LDIwMjYwNDA3LDIwMjYtMDQtMDdUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxhY2NlcHQsNDIwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmQ3M2QyNmQ5LTg4ZWItNWI5ZC04Y2IzLTQzNWViNTBkM2JlOSw3ZDhlZTM1NS02OGZiLTVhMTQtYjI3Yy00NzFmYWMxMGE2ZTYsMjAyNjA0MDgsMjAyNi0wNC0wOFQxNzowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDQ4MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAphYzQ0ZDA3My0yMDM0LTU1MGQtYjE1Yi1mNzljYjhmOTNhMDgsYzE2MjBlZDgtMTI3OC01ZTU4LWEwNGUtNWZlNDFiODNkMTRiLDIwMjYwNDEwLDIwMjYtMDQtMTBUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6Myxlc2NhbGF0ZSw2MDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKZTg0NzQ5ZGUtYzUxMy01OGEyLWEzZWItMjc3MTBmMDIzNzdhLGJmNmQ3MWFlLWRiYzMtNWQ3Yy1hNWI4LTQ4Y2UzN2EzYTFmMiwyMDI2MDQxMSwyMDI2LTA0LTExVDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsNjYwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjBmNmU0MmZiLTRhNGEtNWNkNy1iZGJkLTAwMWMxM2IxMjRjYSwwYmY0ODQyNi0xNDlkLTU5ZGYtODkxZi0wMDJmMzQ1NWVkMDYsMjAyNjA0MTMsMjAyNi0wNC0xM1QxMzowMDowMCswMDowMCxyZXZpZXdlcjoyLGFjY2VwdCwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKOTQ3N2MwMWYtYTZlYy01MzQxLWFmNDQtZTdlMmU5NWVmZDMxLGZmM2M0NDhiLTA1YzktNTU4Yy1hZDkwLTdlMjZkMTQ4ZjQ3MSwyMDI2MDQxNCwyMDI2LTA0LTE0VDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjMsYWNjZXB0LDMwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApiZGVlZjc2NC1kYjcxLTUwODEtOWQ3MC00ZTllMjk3MGQwYWEsZTY3ODhiNjItNDMyNS01OTA0LThiNjktMTQ5MWE4ZjhkNzk3LDIwMjYwNTAxLDIwMjYtMDUtMDFUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxvdmVycmlkZSw0MjAuMCwsUDIsLHN5bnRoZXRpY19vcGVyYXRpb25hbAozY2ZiYjRkYy03MzczLTVmNDMtYWI1OC1hZGQ1Y2QwNTE5YzYsOGQwYTFhOTgtYjhlOS01Njk0LTk0Y2QtMTRlNTljYzUxMzVmLDIwMjYwNTAyLDIwMjYtMDUtMDJUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixhY2NlcHQsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjE0YmUwNmM4LWUwMjYtNTk5Yi05ODQyLTMxNWNlYWUzZjM2MSw3NjIyNzBjMi1jNzA5LTVhMzYtYWY0Ni04NGI4OGU2NzMzNzksMjAyNjA1MDQsMjAyNi0wNS0wNFQxOTowMDowMCswMDowMCxyZXZpZXdlcjo0LGVzY2FsYXRlLDYwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApmYWVmNDEzNS0xZDFiLTU5ODMtYTk1ZS1iODNjZjQ4ZDAxMWYsMjQzNDc1OWItMDg5OS01ZWMxLWEyMzEtZDg4NTZjYzNlODlkLDIwMjYwNTA1LDIwMjYtMDUtMDVUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxlc2NhbGF0ZSw2NjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKYjM4ZGUxNWYtNGRiZi01NzlhLWIzOTQtZTgxNjZiYzgxNjE5LGI3Yjc1YjE1LTM4NzYtNTVlOC04MjIyLTg4ZWUyZGI0ZjBhOSwyMDI2MDUwNywyMDI2LTA1LTA3VDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjMsZXNjYWxhdGUsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmE5ZWZhYWZiLWZjNzMtNTYwMS05ZTdjLTc0N2ExMjEwNjU3Miw5YmZmNmVkOS04ZWUyLTUzYzItYjNlMy1lNzMzOWI1OWFjZjksMjAyNjA1MDgsMjAyNi0wNS0wOFQxNDowMDowMCswMDowMCxyZXZpZXdlcjo0LGFjY2VwdCwzMDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKODJhMzQ3NjYtZGVkMS01NTNjLWIzM2EtMjQwYWExY2Q0NmY2LDgyY2FmOGI2LTBiZDItNTA1NC1hYTllLTI4NGE3NjdhNjUxMiwyMDI2MDUxMCwyMDI2LTA1LTEwVDE2OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsNDIwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmM5OGEzYTcyLTY1MTUtNTcyYy05MDg4LTEwNDQyNzEzZWU3NywxOWU0YzdmMC03NjU1LTU4ZTgtOGU5Ni00YTg3OTc5ZmNjODYsMjAyNjA1MTEsMjAyNi0wNS0xMVQxNzowMDowMCswMDowMCxyZXZpZXdlcjozLGFjY2VwdCw0ODAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKM2Y2MGEzZjAtN2EwYi01MzRjLWFhZDAtYzBiMDcyMWQ5ZmU4LDA5M2QzMjdiLThmNjgtNWRiYS1iODg2LTk2NDc5N2E1OTc4MSwyMDI2MDUxMywyMDI2LTA1LTEzVDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsZXNjYWxhdGUsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjk4OTc2ZGVlLTljNTgtNTJlYi1hNjMzLTViZDIwZWEyZjg2MiwyYjAyNThhMC1hZTMxLTUxNDUtYjUyZS1lOTA2ZWU2ZjI2OGUsMjAyNjA1MTQsMjAyNi0wNS0xNFQyMDowMDowMCswMDowMCxyZXZpZXdlcjoyLG92ZXJyaWRlLDY2MC4wLHdhc3RlX2xpdHRlciwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApmODE2NGMwOS04MTk2LTUwNmYtOTZiZi1mYjE0ZDE1YjI5ZGYsMWEwNWVmNDUtZmFlZi01OWFlLWFjMTYtNTk0MmY1YmI0NmZjLDIwMjYwNjAxLDIwMjYtMDYtMDFUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKYzZlNWJlZmMtYzdiZi01ZWUwLWIxMDItNGRlNzY2ZTMwOTlkLDRhYjU5OWUxLWMxMmEtNWExNC05NmM5LWE2MDIxMzZmODk1NCwyMDI2MDYwMiwyMDI2LTA2LTAyVDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsZXNjYWxhdGUsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjU3OWFjNDU2LWNlNTEtNTI4NC1iMGY4LThjMGVmNmIxZmMxNyw3ZDgyY2I0ZC1lNzBiLTUxNjEtYmJkYy03YWNlNGM4MzU4NzEsMjAyNjA2MDQsMjAyNi0wNi0wNFQxNjowMDowMCswMDowMCxyZXZpZXdlcjozLGFjY2VwdCw0MjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKNjQzZmVjMjItZWNhYy01ZjZmLWE0OGEtMGI0NzQzN2RkY2E0LDExMjVhOTAzLWZlOGItNWFjMy1iMzNmLTI1Yjg5YTg5MmVmNCwyMDI2MDYwNSwyMDI2LTA2LTA1VDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmYzZDVlNmQzLTQ2MDYtNTQyNS04OGI0LWRmZThmYzg0YjYzYyw0OTgyZDIwNi03MTcwLTVjMTQtYmU3MS1kMjQwMTRkN2E1Y2YsMjAyNjA2MDcsMjAyNi0wNi0wN1QxOTowMDowMCswMDowMCxyZXZpZXdlcjoyLGFjY2VwdCw2MDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKZjMxZTUwNGMtOGUzNC01MjhmLWE5ODMtOGQwZGY4MTg1NGQyLGMyODM4YzEzLTVhNTgtNTE3My1hNmE2LWE5MDNkMDczNTFkZiwyMDI2MDYwOCwyMDI2LTA2LTA4VDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjMsZXNjYWxhdGUsNjYwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjNkMjcwZGNjLThmZDAtNWEyNC04MDgyLTgyYzBlZDY0M2Y0NywyOWM1NDhiNy02MDE2LTU3YzMtOTdmMy1iMGRkMTM5YWVlYTIsMjAyNjA2MTAsMjAyNi0wNi0xMFQxMzowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDI0MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo3NmNlZjJjZi01NGE5LTU1ZmItODhmYi00NDg5MjExZTQ2YWMsNTEwMWRhMzQtMTg1Zi01ZmExLTg1YWMtMTljNzEwOGMwM2ZhLDIwMjYwNjExLDIwMjYtMDYtMTFUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSwzMDAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKZjZlYzU0ZjAtNDIyOC01MGU4LTgyYjUtODI3YWMzY2Y2MjZmLDUxM2IxYTZhLTVlOGItNTNlNi1iOGI2LTZlZWU5YzZkYjEzZiwyMDI2MDYxMywyMDI2LTA2LTEzVDE2OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsYWNjZXB0LDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo2MzQzNWI3Mi0wZjE2LTVkODctOTVjOC00NzEwYTQ3NjVmNTcsOTlkOTgxODYtMDFiZS01ODEyLWI5Y2UtZmVmNzg0Y2FiYjg4LDIwMjYwNjE0LDIwMjYtMDYtMTRUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxhY2NlcHQsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjY4MmQzZWViLWM2ZTAtNTA0Yi1iNzJiLTFhMmM4NzhlMjcwMSwyZGNhYjc2Ny1kNjdhLTVlMDMtODMzNS0xNTgwMzdjZTM0NDEsMjAyNjA3MDEsMjAyNi0wNy0wMVQxOTowMDowMCswMDowMCxyZXZpZXdlcjozLGFjY2VwdCw2MDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKMGU0NmM3NjItNmM5OS01NGU4LWFkMWUtMTlhNWE4YTJmMTEyLDkxZjhiNDZmLTAzNmEtNWRmYS04MjUxLTRhNmEzMDIwZmY4NCwyMDI2MDcwMiwyMDI2LTA3LTAyVDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjQsYWNjZXB0LDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo3ZjUzODYzMS02YThhLTVjODYtYjY5Yy1hODY1YWJiOWJhOWEsZTFlODE5ZTktOTI1MS01NjVhLThmM2YtNTUzNDljMTczM2JkLDIwMjYwNzA0LDIwMjYtMDctMDRUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSwyNDAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKOGVkYmNlZjAtMWQ5OS01ZWE3LWFkOTItYWM2MTU0ODA2OTBmLGRkOTQyMzQxLTMxNDYtNTM5My04MmIyLTQzMjFiNWI1MTU4YiwyMDI2MDcwNSwyMDI2LTA3LTA1VDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjMsZXNjYWxhdGUsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjdkZTA1NjE0LTg0ZTUtNTU2Mi1hMWEyLTYwODk0M2JmYjVhYyw5MGI5NmVkNS01NDY1LTVjNTAtOGVkNC0xNGQ1NWE1YmI2NmMsMjAyNjA3MDcsMjAyNi0wNy0wN1QxNjowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo5MWU0NzYzMS04ODJmLTUyMjMtODNjMy04N2JkODVmZWI5NzQsZDdmYTc5MDAtMzkyMC01NjQ3LWJlOGMtMWI3ZjEwZTBjNmRjLDIwMjYwNzA4LDIwMjYtMDctMDhUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixhY2NlcHQsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjc4MjExMGNmLTg2ZGYtNTQzYS04ZTk1LTU3YWJhNTk0MTc4YSwzNzFkZGQxOC0yMjhhLTVjYWMtOTc3YS01MmU2NmI3MDQwZDgsMjAyNjA3MTAsMjAyNi0wNy0xMFQxOTowMDowMCswMDowMCxyZXZpZXdlcjo0LGVzY2FsYXRlLDYwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApmZWZiMjZmZS1hNjFlLTUxYzMtYjVjMS01OGQ4MjFhZWY1YWIsOTFiZTVlODktMmI3Ni01ZmVkLTkyMDItODBhZDk4ODMxOWYyLDIwMjYwNzExLDIwMjYtMDctMTFUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxvdmVycmlkZSw2NjAuMCwsUDIsLHN5bnRoZXRpY19vcGVyYXRpb25hbAowMWZkM2E1OS1iZDBiLTU1MDEtYjcyMi00Mzc0NGNhY2U2MjksOTI5MzJmMjUtOGU0YS01ZTE3LWEyYjYtZjM1NWUyZjc5ZmVkLDIwMjYwNzEzLDIwMjYtMDctMTNUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6Myxlc2NhbGF0ZSwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKM2M1ZjczYjctNmUzOC01YzNiLTk0MWItZGFmZmQ1YzBlMTA4LDFmYTgyZjg1LTY5NGQtNWNkMC1hYThiLTIwNmZhZTc4OTllZCwyMDI2MDcxNCwyMDI2LTA3LTE0VDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjZjMTM5ODhkLTYyNGQtNTMxMC05NDU4LTk3YzFiZjcxNmYyOCxiYmVmYjc0Mi0xMDI1LTUwZjEtOWM4Zi1jOWRlOTAwZDFkZDUsMjAyNjA4MDEsMjAyNi0wOC0wMVQxNjowMDowMCswMDowMCxyZXZpZXdlcjoyLG92ZXJyaWRlLDQyMC4wLHdhc3RlX2xpdHRlciwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAplODhmZDg0OS0zMzQ2LTUxYzAtYjQ3MC02MDMyMjRlZmU3NmQsMDY0MTQzNDQtNWZmYy01NTI3LTljNjQtNWVmYTBlNzg4ZmYyLDIwMjYwODAyLDIwMjYtMDgtMDJUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6Myxlc2NhbGF0ZSw0ODAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKZTYwODQ0YWItNzJkOS01YTFmLWI5NzAtMWJhZTY0NGJkOTk2LDJlMGFhNDNiLTMwYTMtNTczOS1iNzFmLWViZDM2MjVmZWZmMiwyMDI2MDgwNCwyMDI2LTA4LTA0VDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsb3ZlcnJpZGUsNjAwLjAsLFAyLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKYjk3ODRjMTItZmFkOS01ZDE3LWE5YWMtOThjMzBjYmYxYzU5LDE2MGNlYzQzLTg5ZDAtNTMyZC1iNTY4LTk3NGZjY2E2YWY2MiwyMDI2MDgwNSwyMDI2LTA4LTA1VDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsNjYwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsCjllMWEzYzIxLTFiYjEtNWFmMC04Y2I0LTI5MGY0MDEzMWRjYywyMzU5YWY5Yy1hZDc5LTUzZWQtOTdkMC0zYTYyZjVmZjg4NmIsMjAyNjA4MDcsMjAyNi0wOC0wN1QxMzowMDowMCswMDowMCxyZXZpZXdlcjo0LGFjY2VwdCwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKMDkxZGUwNDItZmI5MS01MDAwLTgwMzMtM2EyMTAzYjg3ZDEwLGE1NGJmMzhmLTgwMGQtNWM2Ny04YTcyLTVlNTI5MGFmZTVkMywyMDI2MDgwOCwyMDI2LTA4LTA4VDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsZXNjYWxhdGUsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCmEzNDU4MGM3LWJhNTAtNThkOS05YjQ0LWFiMTU5MWZkMzM3MiwxZjkzOTlmNC1lYzA2LTVmNzUtYTNjNC1jNDA1MjE0Zjg2Y2EsMjAyNjA4MTAsMjAyNi0wOC0xMFQxNjowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbApjN2FiYWU1Ni1hNDNiLTU0MjQtOTA2Ny1hZWU5NDYzMWI5MDgsYjFlMThjZjMtOGRlOS01NGUwLWIxMGMtZGQyZGU0OTZkOGU2LDIwMjYwODExLDIwMjYtMDgtMTFUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSw0ODAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwKNjY4YjIwMTctMDVhNC01ZjNjLWE2ZmItOGVmZjY3NDE0ZDVhLGJlZmU5MjJlLWRkMzgtNTNkNy1iYzg4LWM2Zjg3NjBmYTBmYywyMDI2MDgxMywyMDI2LTA4LTEzVDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsYWNjZXB0LDYwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbAo4YTAzNzMwZS0zMzJiLTU2YzEtYjkwNy05NDJlNzdjYzUxOTMsM2EzNDE4MzQtNTYwZi01NzE5LThmMDAtOTNjNTRlMjYzYWQ3LDIwMjYwODE0LDIwMjYtMDgtMTRUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6MyxhY2NlcHQsNjYwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsCg==", BinaryEncoding.Base64),
			    Raw = Csv.Document(Binary, [Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Raw, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Headers, {"decision_key", "date_key", "review_action", "review_lag_minutes", "data_truth_class"}),
			    Typed = Table.TransformColumnTypes(Selected, {{"decision_key", type text}, {"date_key", Int64.Type}, {"review_action", type text}, {"review_lag_minutes", type number}, {"data_truth_class", type text}}, "en-AU")
			in
			    Typed

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
