table Review
	lineageTag: 5e1b20bc-2ed1-5b75-ab56-fcea102e88a3

	measure 'Review Count' = COUNTROWS(Review)
		formatString: #,0
		lineageTag: 14c30d36-9b4a-52ba-9931-4728704f2f36

	measure 'Median Review Lag' = MEDIAN(Review[review_lag_minutes])
		formatString: #,0 "min"
		lineageTag: b1fae483-d601-5981-b418-ac70d09bd02a

	column decision_key
		dataType: string
		lineageTag: cad87dad-dad2-582c-983a-faa11d8e2dcf
		summarizeBy: none
		sourceColumn: decision_key

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 8da073ce-9187-5e6b-bfc8-27107a0ad7a7
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column review_action
		dataType: string
		lineageTag: 89b174d3-4e3c-588c-9df5-c25c644e6efd
		summarizeBy: none
		sourceColumn: review_action

		annotation SummarizationSetBy = Automatic

	column review_lag_minutes
		dataType: double
		lineageTag: b16992cc-36b0-561e-a8cc-ccab2c7df1bb
		summarizeBy: none
		sourceColumn: review_lag_minutes

		annotation SummarizationSetBy = Automatic

	column data_truth_class
		dataType: string
		lineageTag: 192658ce-dd32-5568-9f53-094c7f9707c7
		summarizeBy: none
		sourceColumn: data_truth_class

		annotation SummarizationSetBy = Automatic

	partition Review-53a7b910-7d08-5767-87c2-6319ad465ebb = m
		mode: import
		source =
			let
			    Binary = Binary.FromText("cmV2aWV3X2tleSxkZWNpc2lvbl9rZXksZGF0ZV9rZXksb2NjdXJyZWRfYXRfdXRjLHJldmlld2VyX2lkLHJldmlld19hY3Rpb24scmV2aWV3X2xhZ19taW51dGVzLGNvcnJlY3RlZF9jYXRlZ29yeSxjb3JyZWN0ZWRfcHJpb3JpdHkscmVwbGFjZW1lbnRfYWN0aW9uLGRhdGFfdHJ1dGhfY2xhc3MNCjkyNDQ5YzU1LWNhMGYtNTk4MC04ODQyLWM4ZmY3NzI1Njg0Yyw5ZTQzZWZhYi0wNDc1LTU1NDEtOTZjNC1kZGU3OTg0MTM3OWMsMjAyNTA5MDEsMjAyNS0wOS0wMVQxMzowMDowMCswMDowMCxyZXZpZXdlcjoxLG92ZXJyaWRlLDI0MC4wLCxQMiwsc3ludGhldGljX29wZXJhdGlvbmFsDQo1YWEwYzhhYi01Njc1LTViYjMtODZhNS0xZjhmYzM4YWJjZjAsMjIyOTAxMDQtMTZhOC01ODkxLWI4MDItMjRlMWI2MzQ4ZTFjLDIwMjUwOTAyLDIwMjUtMDktMDJUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixhY2NlcHQsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQplZTg1MzZlOC02Nzk2LTViMmMtOGI4MS1hMDc3YWZhOGVmMTgsNjY5NTg5ZmEtMmIwZC01M2I5LWE1ZmMtY2JmNTZmZDJmYTdjLDIwMjUwOTA0LDIwMjUtMDktMDRUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSw0MjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjI5NzIxYmY0LTg5MjgtNWQzYi04NjU2LWJmMGY0YmYxYTc0Miw3ODQ1ZDY5Yi1mYTNmLTVhYWItOTRhZi03NjM4OWI5NjA0N2YsMjAyNTA5MDUsMjAyNS0wOS0wNVQxNzowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDQ4MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KZjkwNmZlMDktMTc1OC01OWYxLWI0MmMtZGUxYTI5NDAyMmE2LGI3MjVlY2Y4LTQxMzMtNTlmYi04ZmU0LWVkMTEyMzA2ZGU0NCwyMDI1MDkwNywyMDI1LTA5LTA3VDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjMsZXNjYWxhdGUsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQozYmY1ZTZmMS1lYmFhLTU1YTQtYjExNi00ZDhjMDZjNzRlNmYsOTExOGVlYzktMGEzZS01YjFhLTgzNDQtY2JlZDgwOGU0OTVkLDIwMjUwOTA4LDIwMjUtMDktMDhUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxhY2NlcHQsNjYwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQoxZjdiMzE1Mi1kYjhhLTVkYzgtYWEzYy1lZjVhYzBjNjVlYTMsNTYwNTA0MzctNWVkYy01MTUwLTg1ODktOGExOWI0N2M1MDkxLDIwMjUwOTEwLDIwMjUtMDktMTBUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSwyNDAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmU5OThjNDA0LTNlYWItNTk4YS04ZDU3LTg4MDQ4NWNlOTQyMyxjMjUxMWY4Mi1jZDliLTU0ZDMtYjBlMy02ZTRjYWUzYTRkNTMsMjAyNTA5MTEsMjAyNS0wOS0xMVQxNDowMDowMCswMDowMCxyZXZpZXdlcjozLGFjY2VwdCwzMDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmQyMGIyYzY1LTVjODYtNWJkNS05Zjc4LTFjMDY5YzhhMzNkOCwwN2QxNTgzOC1kNzBlLTVjYTMtYjZhYy01MzRkNzI3MTZhNDcsMjAyNTA5MTMsMjAyNS0wOS0xM1QxNjowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KZWNiNzQ1MmYtNDQ5ZC01ZDUwLWJlNmYtNDJmM2Y0NWQ4MTEwLDI2NDUyMGI0LWJiZDMtNTAzMi05NTk0LWU1NmNjMTMyZWFjZiwyMDI1MDkxNCwyMDI1LTA5LTE0VDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsNDgwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo3ZjAyZmFjNi0zMTJjLTUzMTItYmUyOC0xMjIxZGU3NWZhZGUsMzZiMWEyNzYtYzk4ZS01ODkxLWI3MzEtOThmNjM4YWE0ZDgyLDIwMjUxMDAxLDIwMjUtMTAtMDFUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSw2MDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjZlOTI1MTIxLTA3NDAtNTIzOS1hYTQ4LTc2Yzg1YWM0Njc4MCwwYTBmZTUzYS00YTBiLTU2MWUtOWQ3NS00MzkxODIzNzY2YjUsMjAyNTEwMDIsMjAyNS0xMC0wMlQyMDowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KMWFkODc3YzUtYzlmZC01YjQ5LTkzYzItN2IyMTVlM2U1MzcxLGRkMTllYjViLTUxOTUtNTliMC1hNDQ1LTBlMDIwN2RmOGIzNiwyMDI1MTAwNCwyMDI1LTEwLTA0VDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjMsYWNjZXB0LDI0MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KYzdjOWJkNzgtZmRmMS01Yjk0LWI0NjYtMTQ2MmQyZjlhMDBiLGViOGM4YjFmLTc3ZjYtNTQ1Yy05MzM5LTg2NDNkYjExNmNjYSwyMDI1MTAwNSwyMDI1LTEwLTA1VDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQoxOGZjYzM2MS05NWVlLTVjODAtYmM2ZS05NTE2MTg5M2ExYzksYmQ1OGNmNjQtMjkzOC01ODJmLTg3YTMtODBmODhkMDhlMTQxLDIwMjUxMDA3LDIwMjUtMTAtMDdUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixhY2NlcHQsNDIwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpmMzdhMjgxOC0xOTYwLTUzNzUtOGMyYi1iODJjNjhkMjk3MTcsMjczMjdhOTItYTVhZi01ZDExLWEwOGYtYWE3Zjk5NGNkOTg3LDIwMjUxMDA4LDIwMjUtMTAtMDhUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6Myxlc2NhbGF0ZSw0ODAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmEyYzJkN2VkLTA0OGYtNTNhOC1hZGRiLTNmMmYyYjFhMWNmNCw0M2ZjMmNkMC1mODI4LTUzNzgtYTNlYS0yNGUzNGM4OTU3ODMsMjAyNTEwMTAsMjAyNS0xMC0xMFQxOTowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDYwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KMTk5NjVjYzktMzliYi01Y2YzLThjZTYtNGZjM2NiODQ3MjFiLDYwOTAzNDlhLWI2NGEtNTg0Mi05OWJiLTk1MmI2NzAxMTRjNCwyMDI1MTAxMSwyMDI1LTEwLTExVDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsNjYwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpjMjU4ODQ2NC03NGRjLTU4MTUtYjQ4ZC1lZWQ3YjBkOGU3N2IsMzczNThjYWItMjllNC01NTVlLTliMDMtNmQ2MmFmM2QwYTg1LDIwMjUxMDEzLDIwMjUtMTAtMTNUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxhY2NlcHQsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpiNzg5NDEyYy0zNmM4LTU0N2ItODVkOC1mOWI3NWQxZjhlNzUsYzk2MjRlMzEtNjdmNi01OWNmLWE4MmMtMzFhZGI5NTk3MzE2LDIwMjUxMDE0LDIwMjUtMTAtMTRUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxhY2NlcHQsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo5ZTE5ZjU5Mi1lOTMwLTUyNmYtYmFmZi1hNjJiMGU0MWFlODksNmI4Zjk2NjgtNTZhMS01NjRjLWFkN2ItYzMzNDNkZTczM2FlLDIwMjUxMTAxLDIwMjUtMTEtMDFUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6MyxhY2NlcHQsNDIwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo2MjUzMjE0YS01ZTBmLTUzY2ItODQ1Mi1kYTRmMmRlODYwMmEsMmQ5ZjI5OTctOWY1Yi01NTQ4LWI2ODktNWEwM2ZjZDFmNzFmLDIwMjUxMTAyLDIwMjUtMTEtMDJUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxhY2NlcHQsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpjMmFiNzNmNi03NDIyLTUwNTAtOGE1MC0zZjBjMDhlOTQ3MjIsNjhhOWE5NGMtMGRmMy01NzRhLWJjYTUtYTRhOWQwNWQzYzViLDIwMjUxMTA0LDIwMjUtMTEtMDRUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSw2MDAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmE5YWVjNWFhLTU1OGMtNWEyNC1iMjc2LTVhYjg0OGUxYWZjZSxkN2U1NWI1Yy05NTAxLTVjNDQtOGM4Zi1lYzE3YmZlYzY3ODAsMjAyNTExMDUsMjAyNS0xMS0wNVQyMDowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KNTE3M2Q5MDgtYTAyMC01NGIxLThkOGQtOWE4ZmNiMDExYzE1LGRjMjA3Y2JmLWMxMDEtNTI4My04NmJhLWVhMDNmMTg2MzA1YywyMDI1MTEwNywyMDI1LTExLTA3VDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjEsZXNjYWxhdGUsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo3YTMzMTE3Zi05ZDQ5LTU5NzUtOTNjMi02MTAxNmFhNDBkNTYsYzJkOTE4ZTUtNmM4MC01MjdhLWE2NzUtMjU3MmIzMzA4Y2JmLDIwMjUxMTA4LDIwMjUtMTEtMDhUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixhY2NlcHQsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQplYTQ0YmNiNy0zNDhhLTVmZDYtOTJiYS0xYjIyMzJhNDRiODgsYWUwY2UwZTgtNWE4Yy01ZmJlLWE0MjQtNDhlOTI4OTVjZDc3LDIwMjUxMTEwLDIwMjUtMTEtMTBUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSw0MjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmM0MjIxN2EzLTZkMTQtNTdhNi1hYzRiLTlkZDNmZWE1MjQ1ZSw5MDI2NWNhNy02OTNjLTU3NTgtOTA5My1lYTIyMTE0OGQxOTIsMjAyNTExMTEsMjAyNS0xMS0xMVQxNzowMDowMCswMDowMCxyZXZpZXdlcjoxLG92ZXJyaWRlLDQ4MC4wLCxQMiwsc3ludGhldGljX29wZXJhdGlvbmFsDQowY2YxYmRkMC00YzIwLTUyZTktYWYyZC04YzkzYWQyOTM1MWEsZTUyNGNjODUtZWIyNi01NmRmLWI0NjEtMjgyMjE4MjUxZTA4LDIwMjUxMTEzLDIwMjUtMTEtMTNUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6Myxlc2NhbGF0ZSw2MDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjI1ZTk1Mzc0LThkODgtNWQ5ZC05NWI5LTNiNzkyMmEyNTg4NCw0NWI3NzZmMS00ZDcyLTU0ZTYtOTU5My1kNGEyMzBlMWE4YjAsMjAyNTExMTQsMjAyNS0xMS0xNFQyMDowMDowMCswMDowMCxyZXZpZXdlcjo0LGVzY2FsYXRlLDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KNmJmM2ZhMGEtZTNiMi01NTZmLTk0MzYtMGY2YzEyZDYyZWE1LGJmYzdiZjBiLWRhMzUtNTgxZC1iZDkwLWYxZTBkMTQwZTEzZSwyMDI1MTIwMSwyMDI1LTEyLTAxVDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsMjQwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQozYTM5MjVkOS0yODIwLTU1YTQtODFjNi1iNzg1MzA2ZjVhOWQsNTYyODdiZTUtZmUyNi01Y2Y1LWJiZTQtYWYzMDgzNTNhZDhiLDIwMjUxMjAyLDIwMjUtMTItMDJUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6Myxlc2NhbGF0ZSwzMDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjI3ZDdjZjQ3LWZhOTQtNTkyZS1iZjFhLTQ2MDdmZmZjMGU4NywyZDM1YmU0Ni1jZGE3LTU3ZTMtYmYzYS03ZTc1MDRiMjExMTksMjAyNTEyMDQsMjAyNS0xMi0wNFQxNjowMDowMCswMDowMCxyZXZpZXdlcjoxLG92ZXJyaWRlLDQyMC4wLCxQMiwsc3ludGhldGljX29wZXJhdGlvbmFsDQpjZTljODA4ZC03NDlkLTViOWUtODI2OC02YmU3NTk0NDJiMzYsZDc0OGFjYjgtMjAxYy01N2MyLWEyZjYtODBhZDdlNTlhOTVmLDIwMjUxMjA1LDIwMjUtMTItMDVUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSw0ODAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmRhYTI0MjliLTQ3NzctNTQ4MC1iYmY5LWNlOWY5YmM1MzM1MSw0Mzk1MTVjMy03MzcyLTVkMzctODFhYS1lMTY1ZWFiZDU3MjUsMjAyNTEyMDcsMjAyNS0xMi0wN1QxOTowMDowMCswMDowMCxyZXZpZXdlcjo0LGFjY2VwdCw2MDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjFlODFhMmE5LTA1NmEtNTgxMi05MjFmLWNiMTZmMjc5OTFlZiw5NWVkNDdmNC1mMDQ0LTVmNGUtOGU5NS0xNjBhN2Y3NDVhMDcsMjAyNTEyMDgsMjAyNS0xMi0wOFQyMDowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KZTljZDdiMmQtYTgyZS01OTliLWJlM2MtMzJkYThiMzNkMjU5LDYzYzg3YjNmLTViZTQtNTU5Ny1hOWY3LWU0OTJiYzUyOWQyNSwyMDI1MTIxMCwyMDI1LTEyLTEwVDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjMsZXNjYWxhdGUsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo2MTNlNGI5NC02NDJlLTVjNzktYmZhMy05MGFjNjNiMTM0YjksODcxOTU4Y2ItYTgyOC01YWFmLTkzZmUtZmJiZGIyZjBhNGFiLDIwMjUxMjExLDIwMjUtMTItMTFUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSwzMDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjQwYTBjMzllLTc2MGMtNWQ0My1hNWI5LTBiZjM5ZDc1ZGQ4OCw0ZWMyNGY0Mi04MTgwLTU4MmQtODUxMi04Y2E1YTdiZTgxOGUsMjAyNTEyMTMsMjAyNS0xMi0xM1QxNjowMDowMCswMDowMCxyZXZpZXdlcjoyLGFjY2VwdCw0MjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjBiMzUxOTA0LWE5MmUtNTM4ZC05N2M5LWY5ZWQ5YjdlZjUwNCw4YTBjMTQyNC04ZWNkLTVhYzgtODIwMy1lNzlhMjNlZWUyZmUsMjAyNTEyMTQsMjAyNS0xMi0xNFQxNzowMDowMCswMDowMCxyZXZpZXdlcjozLGFjY2VwdCw0ODAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmYyYWEyYTk1LWE1MjYtNTFiMy1hMmU5LWU0YjA0Yjc4MDQ0YixmNGM1ZWJmOC0zZDc5LTViMWUtODgyMy02ZDk1YWI5YmJmNWQsMjAyNjAxMDEsMjAyNi0wMS0wMVQxOTowMDowMCswMDowMCxyZXZpZXdlcjoxLGFjY2VwdCw2MDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjEyNTQxMTZmLTg4N2YtNTI1ZC05NWZlLWYxODczOWYyOWVjYSwyNTlkZDdmZC0yZjY5LTU1NGItODU3Zi03MjMyMjZhMjM3ZmYsMjAyNjAxMDIsMjAyNi0wMS0wMlQyMDowMDowMCswMDowMCxyZXZpZXdlcjoyLGFjY2VwdCw2NjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjA4ZmM5OGY2LWU3OGItNTM3MS1hMzllLTA3YzMyZDUzN2ZmYixmMmE1N2Y1MS1hZjJhLTUyNzQtODM0NS0wYTlkMzEzZmI0MmEsMjAyNjAxMDQsMjAyNi0wMS0wNFQxMzowMDowMCswMDowMCxyZXZpZXdlcjo0LGVzY2FsYXRlLDI0MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KZjRiMjZlMDUtNTQ2Mi01N2ViLTliNzAtYmEyMTg5ZjEyY2VlLDY3YmI2YzhiLTM3YjEtNWJjNS1iNDIzLTc0YjYzMTI2ZGRkZCwyMDI2MDEwNSwyMDI2LTAxLTA1VDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsZXNjYWxhdGUsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpmZWY5MWY4Zi1mN2U2LTU5MGUtOTg2NS00M2JmNmQ5ZDQyZmQsZDRkMTllZWQtYjM5Ni01YTRjLTkxMjEtZWU1MjgwNWQ1NWMzLDIwMjYwMTA3LDIwMjYtMDEtMDdUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6Myxlc2NhbGF0ZSw0MjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjRmMTgxMzFiLTEyODgtNTg1Ny05YWE5LTA5ODZmZDkzZTYzOCw5YTY4OGZmNS05NjNjLTUxZTktOGE5Ni1mMjUyYmM5YTBkY2EsMjAyNjAxMDgsMjAyNi0wMS0wOFQxNzowMDowMCswMDowMCxyZXZpZXdlcjo0LGFjY2VwdCw0ODAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmNkMTI4NjRmLTFmNDQtNTBlNy04NTBkLTlmMDA1NGQ5OGQ5Yyw1OTI3YjZjZS1hOTU0LTU3OTgtOWQ4NC0xZjRlNTk0NzRhNzQsMjAyNjAxMTAsMjAyNi0wMS0xMFQxOTowMDowMCswMDowMCxyZXZpZXdlcjoyLG92ZXJyaWRlLDYwMC4wLHdhc3RlX2xpdHRlciwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KNWQ0YWE3MmEtODQ0Zi01MTVhLTg0YjAtMjFjNmMwYWRmYmMzLDFmMDc4ZDkxLTE1MzEtNTY4OC04Yzg3LTBjOGIyNTQ1NmI4OCwyMDI2MDExMSwyMDI2LTAxLTExVDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjMsYWNjZXB0LDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KNWRjYjg2ZmQtNGRmYi01MDU3LTkxNjMtYjg1YjAyN2U3NjU0LDBlMjgwNGU5LWY3NjItNTI0OC1iNWI5LTRmMWVlMjNmNzg0ZCwyMDI2MDExMywyMDI2LTAxLTEzVDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjEsZXNjYWxhdGUsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQoxODA3ZjRiYi0yOTc1LTU5OWEtOGQ1YS04YThhNTI0ZjhmODMsMDk3MmYwNjgtNGNhNi01YWYyLWI3M2YtNmVhMTM5MjRlMjY2LDIwMjYwMTE0LDIwMjYtMDEtMTRUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSwzMDAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjI3YTc3MjA5LTQ0MmYtNTRhMS1hZDk4LTFiOGViNmNmZjlmYywwMTEwMGFlMC1jMTA4LTU4NTItYjBkMC02MDQxNDk3ZmI0NGEsMjAyNjAyMDEsMjAyNi0wMi0wMVQxNjowMDowMCswMDowMCxyZXZpZXdlcjo0LGVzY2FsYXRlLDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KYjJmODdkMTEtYWUwNC01YWQ1LTg2MDgtYzYyNjkyYzZlNDBlLGNiY2M1OWM4LTdjZTgtNTVmMC04NDlhLWQ0ZTg5NDk3MmU0MCwyMDI2MDIwMiwyMDI2LTAyLTAyVDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsZXNjYWxhdGUsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpjMmQyZjJjNC0wZjA1LTViMzQtODNjZS0zMWJhOTcyNTU0NTcsNmFhMWI1NmQtZmU1OS01YTlhLTgwYTEtMjVhMmI2N2RlYmE3LDIwMjYwMjA0LDIwMjYtMDItMDRUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6MyxhY2NlcHQsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo0MzNmMWFkMC1lODViLTU3ZWEtYWJjMS1lOWY3NTJmZGExOWIsZmM5YzRlY2QtYzc4NS01NWM3LTliZDItN2M3ODZkYzhlODBjLDIwMjYwMjA1LDIwMjYtMDItMDVUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSw2NjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjJiYWFmZmE0LWJjZjUtNTFkOS04MWNlLWZmNjdjNmRkMTM0MywyM2YwZjQ3OC1lZTRlLTVhYmQtOWU2OS0zMTYzZDZiYmEwOTQsMjAyNjAyMDcsMjAyNi0wMi0wN1QxMzowMDowMCswMDowMCxyZXZpZXdlcjoyLGFjY2VwdCwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjQzZDg0ZmVlLTE0NGEtNWMxOC1iMGU1LWVmOGRiYzA5NDY1NCw4MjVhNDFlNC1mMDBkLTUyOWItOGIwNC02NDgxMTZjY2ZkZjIsMjAyNjAyMDgsMjAyNi0wMi0wOFQxNDowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDMwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KYTAxZDJhZTctZGEwZS01ODQyLWJjYzctNzM2N2YzYjgyYmRlLGUxNjg0MWM2LWI4YzgtNWY2Mi05OWMxLTMwNWMzZmVjZjU0OSwyMDI2MDIxMCwyMDI2LTAyLTEwVDE2OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsZXNjYWxhdGUsNDIwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo1NjE5OGY3ZC1hNDg0LTU5MDMtODc4MC04ODMwMTE0NzJjYTgsNzIxODcyMWUtOGYyNy01MmRhLWE1OGQtOGU5Njk4M2JjNzg1LDIwMjYwMjExLDIwMjYtMDItMTFUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSw0ODAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmI4NGY1ODJjLTgyZmItNTE1NS1hNzg5LWUxN2NhNjkyNDcwYSw5NjE1MTY1My03NDliLTU5YWQtYjljZC1lZWU1MDEwMjc3YjAsMjAyNjAyMTMsMjAyNi0wMi0xM1QxOTowMDowMCswMDowMCxyZXZpZXdlcjo0LGFjY2VwdCw2MDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjk0MDMwY2NhLTQ2MTEtNTkwOS1iNTc1LTM2ZDhmOWVlZWNiNSxlMmJmMDczYS1hZmFjLTVmYzItOTJhNS00MTZlMGQyNWUyZjMsMjAyNjAyMTQsMjAyNi0wMi0xNFQyMDowMDowMCswMDowMCxyZXZpZXdlcjoxLG92ZXJyaWRlLDY2MC4wLCxQMiwsc3ludGhldGljX29wZXJhdGlvbmFsDQoyMTI4ODQ5Mi01ODI2LTUwZTMtYjAzYi1jNjY1OTczNmI1NDAsN2IzODM2NzgtNzVhMy01MDAwLTkyNWItNGJiYWRhY2FjYjU5LDIwMjYwMzAxLDIwMjYtMDMtMDFUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6MyxhY2NlcHQsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpjNmZiOWFhMS02MTU1LTU4MjQtYTA0NC0xZTk1NGI1ODM3YzMsYWMwMjExZmQtMzhlNS01NzgyLTgyMWQtZTVlMTQ2ZmYxZGE3LDIwMjYwMzAyLDIwMjYtMDMtMDJUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxhY2NlcHQsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQowYTg0N2U4NC02NzY4LTUyNGItYmJmMC0xMzAyNGQ5OWM1ODksMzI3Mjg0MjAtOGVjMC01MmE2LWE1YzMtYWQyODJhZWJhYjcyLDIwMjYwMzA0LDIwMjYtMDMtMDRUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSw0MjAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjRlZjVhZmYyLWYxYjItNTBlZC05YjVjLTI0ZTMyNmRiYTBkMiwxNzE5MTJhZS0wZWNmLTUyNDEtYTg2MS02NGE4OGE4OTk0OWEsMjAyNjAzMDUsMjAyNi0wMy0wNVQxNzowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDQ4MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KYTc2Y2E4ZDYtMzQ5Yi01ZDRlLTgyMGMtYTkxMzBlZWJiNzcwLDMzZmVmNjRjLWE4MWItNWI4Zi05ODVlLTZlNjBjNDkzNTExMSwyMDI2MDMwNywyMDI2LTAzLTA3VDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsZXNjYWxhdGUsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQozMWUxZjNmMy1kMzhmLTUxM2MtODM5My0yMTE4NDk5YTIwODIsN2RmMjZlM2YtZWQ5Yi01ZmJmLThhYjctYjE0YWRhZTFmYWFkLDIwMjYwMzA4LDIwMjYtMDMtMDhUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixhY2NlcHQsNjYwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo5MjNlM2NkYy05MTkwLTViZDgtOGYzZi03OTM1OWY0OTA1NzAsMzIzNDY0MzItZmRiNC01YzFlLWJkY2MtNzM4NTBiMTQzMmU4LDIwMjYwMzEwLDIwMjYtMDMtMTBUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjVmNDQzNWNiLTNlNTktNTAwNy04YjIyLWJkYmYwMWFiMzhjMCxjMWVjZTlhMS04NTZmLTU5OTMtYWVkMy0yZTkzMGVmNWU2N2EsMjAyNjAzMTEsMjAyNi0wMy0xMVQxNDowMDowMCswMDowMCxyZXZpZXdlcjoxLGFjY2VwdCwzMDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmRmYmZlZGVmLTljYzQtNTExNi05YTYyLTdkMDA5OTIwNmEwZSw4NGFhYTVhOC1lZWE3LTU4NzItODYwNi1kZDg1YWIyYWY5M2IsMjAyNjAzMTMsMjAyNi0wMy0xM1QxNjowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KNDdjNjUzZGMtZGIyYy01ZjQzLTg0OTYtN2MxNGEwYWQ3MjlmLDc0MzdlZTk5LTdlYzAtNWZlNC1iYjU2LTNmODk1YThmN2VkOSwyMDI2MDMxNCwyMDI2LTAzLTE0VDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQphZDE3NGM3YS01OWQ2LTUyYjQtYmY4ZC04YzJhYmU1ODZiNmQsYjhhOTg2MzktMmNkMi01NmIxLTg3OGItZDdmNDU2NDY3OTMwLDIwMjYwNDAxLDIwMjYtMDQtMDFUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixvdmVycmlkZSw2MDAuMCx3YXN0ZV9saXR0ZXIsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjFmZTUzNDI5LThjOTgtNTBlOC1hYTJmLTQ2NDYzNTFjNWVhNiw3ZjY0MmRiYi01ZjQxLTUyYTMtYTA4Ni0yNjdjZTZjMjRhODksMjAyNjA0MDIsMjAyNi0wNC0wMlQyMDowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KYWRhYTk5ZTUtNDllYy01YjQ2LTgyOGEtZjU5MzkyNWE4YmZiLDIyNjI1YWIzLWI3MTItNWNkNy1hYTZiLTExMjQ2ODMyZDA0MywyMDI2MDQwNCwyMDI2LTA0LTA0VDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjEsYWNjZXB0LDI0MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KMzNkODJjZjgtMTQ4NS01NzYyLWIwN2EtZjA1MjM5ZmE1ZThmLGRlODc3MGJlLWQ5MjItNTY1NC1iMzJlLWVjZDk1OWZjZjg0ZSwyMDI2MDQwNSwyMDI2LTA0LTA1VDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsMzAwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpkZDA5Yjk4MC01OWFhLTVjZmQtOTBhYi1hYzQzYzAzMjRkMjQsZDYyODA0OGQtZDNhOS01ZDlmLTlhZDUtOTM4ZGE1MTU4MTg1LDIwMjYwNDA3LDIwMjYtMDQtMDdUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxhY2NlcHQsNDIwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpkNzNkMjZkOS04OGViLTViOWQtOGNiMy00MzVlYjUwZDNiZTksN2Q4ZWUzNTUtNjhmYi01YTE0LWIyN2MtNDcxZmFjMTBhNmU2LDIwMjYwNDA4LDIwMjYtMDQtMDhUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxlc2NhbGF0ZSw0ODAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmFjNDRkMDczLTIwMzQtNTUwZC1iMTViLWY3OWNiOGY5M2EwOCxjMTYyMGVkOC0xMjc4LTVlNTgtYTA0ZS01ZmU0MWI4M2QxNGIsMjAyNjA0MTAsMjAyNi0wNC0xMFQxOTowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDYwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KZTg0NzQ5ZGUtYzUxMy01OGEyLWEzZWItMjc3MTBmMDIzNzdhLGJmNmQ3MWFlLWRiYzMtNWQ3Yy1hNWI4LTQ4Y2UzN2EzYTFmMiwyMDI2MDQxMSwyMDI2LTA0LTExVDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsNjYwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQowZjZlNDJmYi00YTRhLTVjZDctYmRiZC0wMDFjMTNiMTI0Y2EsMGJmNDg0MjYtMTQ5ZC01OWRmLTg5MWYtMDAyZjM0NTVlZDA2LDIwMjYwNDEzLDIwMjYtMDQtMTNUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixhY2NlcHQsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo5NDc3YzAxZi1hNmVjLTUzNDEtYWY0NC1lN2UyZTk1ZWZkMzEsZmYzYzQ0OGItMDVjOS01NThjLWFkOTAtN2UyNmQxNDhmNDcxLDIwMjYwNDE0LDIwMjYtMDQtMTRUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6MyxhY2NlcHQsMzAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpiZGVlZjc2NC1kYjcxLTUwODEtOWQ3MC00ZTllMjk3MGQwYWEsZTY3ODhiNjItNDMyNS01OTA0LThiNjktMTQ5MWE4ZjhkNzk3LDIwMjYwNTAxLDIwMjYtMDUtMDFUMTY6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxvdmVycmlkZSw0MjAuMCwsUDIsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KM2NmYmI0ZGMtNzM3My01ZjQzLWFiNTgtYWRkNWNkMDUxOWM2LDhkMGExYTk4LWI4ZTktNTY5NC05NGNkLTE0ZTU5Y2M1MTM1ZiwyMDI2MDUwMiwyMDI2LTA1LTAyVDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsYWNjZXB0LDQ4MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KMTRiZTA2YzgtZTAyNi01OTliLTk4NDItMzE1Y2VhZTNmMzYxLDc2MjI3MGMyLWM3MDktNWEzNi1hZjQ2LTg0Yjg4ZTY3MzM3OSwyMDI2MDUwNCwyMDI2LTA1LTA0VDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpmYWVmNDEzNS0xZDFiLTU5ODMtYTk1ZS1iODNjZjQ4ZDAxMWYsMjQzNDc1OWItMDg5OS01ZWMxLWEyMzEtZDg4NTZjYzNlODlkLDIwMjYwNTA1LDIwMjYtMDUtMDVUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxlc2NhbGF0ZSw2NjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmIzOGRlMTVmLTRkYmYtNTc5YS1iMzk0LWU4MTY2YmM4MTYxOSxiN2I3NWIxNS0zODc2LTU1ZTgtODIyMi04OGVlMmRiNGYwYTksMjAyNjA1MDcsMjAyNi0wNS0wN1QxMzowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDI0MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KYTllZmFhZmItZmM3My01NjAxLTllN2MtNzQ3YTEyMTA2NTcyLDliZmY2ZWQ5LThlZTItNTNjMi1iM2UzLWU3MzM5YjU5YWNmOSwyMDI2MDUwOCwyMDI2LTA1LTA4VDE0OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsYWNjZXB0LDMwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KODJhMzQ3NjYtZGVkMS01NTNjLWIzM2EtMjQwYWExY2Q0NmY2LDgyY2FmOGI2LTBiZDItNTA1NC1hYTllLTI4NGE3NjdhNjUxMiwyMDI2MDUxMCwyMDI2LTA1LTEwVDE2OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsNDIwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpjOThhM2E3Mi02NTE1LTU3MmMtOTA4OC0xMDQ0MjcxM2VlNzcsMTllNGM3ZjAtNzY1NS01OGU4LThlOTYtNGE4Nzk3OWZjYzg2LDIwMjYwNTExLDIwMjYtMDUtMTFUMTc6MDA6MDArMDA6MDAscmV2aWV3ZXI6MyxhY2NlcHQsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQozZjYwYTNmMC03YTBiLTUzNGMtYWFkMC1jMGIwNzIxZDlmZTgsMDkzZDMyN2ItOGY2OC01ZGJhLWI4ODYtOTY0Nzk3YTU5NzgxLDIwMjYwNTEzLDIwMjYtMDUtMTNUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxlc2NhbGF0ZSw2MDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjk4OTc2ZGVlLTljNTgtNTJlYi1hNjMzLTViZDIwZWEyZjg2MiwyYjAyNThhMC1hZTMxLTUxNDUtYjUyZS1lOTA2ZWU2ZjI2OGUsMjAyNjA1MTQsMjAyNi0wNS0xNFQyMDowMDowMCswMDowMCxyZXZpZXdlcjoyLG92ZXJyaWRlLDY2MC4wLHdhc3RlX2xpdHRlciwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KZjgxNjRjMDktODE5Ni01MDZmLTk2YmYtZmIxNGQxNWIyOWRmLDFhMDVlZjQ1LWZhZWYtNTlhZS1hYzE2LTU5NDJmNWJiNDZmYywyMDI2MDYwMSwyMDI2LTA2LTAxVDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpjNmU1YmVmYy1jN2JmLTVlZTAtYjEwMi00ZGU3NjZlMzA5OWQsNGFiNTk5ZTEtYzEyYS01YTE0LTk2YzktYTYwMjEzNmY4OTU0LDIwMjYwNjAyLDIwMjYtMDYtMDJUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxlc2NhbGF0ZSwzMDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjU3OWFjNDU2LWNlNTEtNTI4NC1iMGY4LThjMGVmNmIxZmMxNyw3ZDgyY2I0ZC1lNzBiLTUxNjEtYmJkYy03YWNlNGM4MzU4NzEsMjAyNjA2MDQsMjAyNi0wNi0wNFQxNjowMDowMCswMDowMCxyZXZpZXdlcjozLGFjY2VwdCw0MjAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjY0M2ZlYzIyLWVjYWMtNWY2Zi1hNDhhLTBiNDc0MzdkZGNhNCwxMTI1YTkwMy1mZThiLTVhYzMtYjMzZi0yNWI4OWE4OTJlZjQsMjAyNjA2MDUsMjAyNi0wNi0wNVQxNzowMDowMCswMDowMCxyZXZpZXdlcjo0LGVzY2FsYXRlLDQ4MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KZjNkNWU2ZDMtNDYwNi01NDI1LTg4YjQtZGZlOGZjODRiNjNjLDQ5ODJkMjA2LTcxNzAtNWMxNC1iZTcxLWQyNDAxNGQ3YTVjZiwyMDI2MDYwNywyMDI2LTA2LTA3VDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsYWNjZXB0LDYwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KZjMxZTUwNGMtOGUzNC01MjhmLWE5ODMtOGQwZGY4MTg1NGQyLGMyODM4YzEzLTVhNTgtNTE3My1hNmE2LWE5MDNkMDczNTFkZiwyMDI2MDYwOCwyMDI2LTA2LTA4VDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjMsZXNjYWxhdGUsNjYwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQozZDI3MGRjYy04ZmQwLTVhMjQtODA4Mi04MmMwZWQ2NDNmNDcsMjljNTQ4YjctNjAxNi01N2MzLTk3ZjMtYjBkZDEzOWFlZWEyLDIwMjYwNjEwLDIwMjYtMDYtMTBUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxlc2NhbGF0ZSwyNDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjc2Y2VmMmNmLTU0YTktNTVmYi04OGZiLTQ0ODkyMTFlNDZhYyw1MTAxZGEzNC0xODVmLTVmYTEtODVhYy0xOWM3MTA4YzAzZmEsMjAyNjA2MTEsMjAyNi0wNi0xMVQxNDowMDowMCswMDowMCxyZXZpZXdlcjoyLG92ZXJyaWRlLDMwMC4wLHdhc3RlX2xpdHRlciwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KZjZlYzU0ZjAtNDIyOC01MGU4LTgyYjUtODI3YWMzY2Y2MjZmLDUxM2IxYTZhLTVlOGItNTNlNi1iOGI2LTZlZWU5YzZkYjEzZiwyMDI2MDYxMywyMDI2LTA2LTEzVDE2OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsYWNjZXB0LDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KNjM0MzViNzItMGYxNi01ZDg3LTk1YzgtNDcxMGE0NzY1ZjU3LDk5ZDk4MTg2LTAxYmUtNTgxMi1iOWNlLWZlZjc4NGNhYmI4OCwyMDI2MDYxNCwyMDI2LTA2LTE0VDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjEsYWNjZXB0LDQ4MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KNjgyZDNlZWItYzZlMC01MDRiLWI3MmItMWEyYzg3OGUyNzAxLDJkY2FiNzY3LWQ2N2EtNWUwMy04MzM1LTE1ODAzN2NlMzQ0MSwyMDI2MDcwMSwyMDI2LTA3LTAxVDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjMsYWNjZXB0LDYwMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KMGU0NmM3NjItNmM5OS01NGU4LWFkMWUtMTlhNWE4YTJmMTEyLDkxZjhiNDZmLTAzNmEtNWRmYS04MjUxLTRhNmEzMDIwZmY4NCwyMDI2MDcwMiwyMDI2LTA3LTAyVDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjQsYWNjZXB0LDY2MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KN2Y1Mzg2MzEtNmE4YS01Yzg2LWI2OWMtYTg2NWFiYjliYTlhLGUxZTgxOWU5LTkyNTEtNTY1YS04ZjNmLTU1MzQ5YzE3MzNiZCwyMDI2MDcwNCwyMDI2LTA3LTA0VDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsMjQwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo4ZWRiY2VmMC0xZDk5LTVlYTctYWQ5Mi1hYzYxNTQ4MDY5MGYsZGQ5NDIzNDEtMzE0Ni01MzkzLTgyYjItNDMyMWI1YjUxNThiLDIwMjYwNzA1LDIwMjYtMDctMDVUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6Myxlc2NhbGF0ZSwzMDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjdkZTA1NjE0LTg0ZTUtNTU2Mi1hMWEyLTYwODk0M2JmYjVhYyw5MGI5NmVkNS01NDY1LTVjNTAtOGVkNC0xNGQ1NWE1YmI2NmMsMjAyNjA3MDcsMjAyNi0wNy0wN1QxNjowMDowMCswMDowMCxyZXZpZXdlcjoxLGVzY2FsYXRlLDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KOTFlNDc2MzEtODgyZi01MjIzLTgzYzMtODdiZDg1ZmViOTc0LGQ3ZmE3OTAwLTM5MjAtNTY0Ny1iZThjLTFiN2YxMGUwYzZkYywyMDI2MDcwOCwyMDI2LTA3LTA4VDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjIsYWNjZXB0LDQ4MC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KNzgyMTEwY2YtODZkZi01NDNhLThlOTUtNTdhYmE1OTQxNzhhLDM3MWRkZDE4LTIyOGEtNWNhYy05NzdhLTUyZTY2YjcwNDBkOCwyMDI2MDcxMCwyMDI2LTA3LTEwVDE5OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQpmZWZiMjZmZS1hNjFlLTUxYzMtYjVjMS01OGQ4MjFhZWY1YWIsOTFiZTVlODktMmI3Ni01ZmVkLTkyMDItODBhZDk4ODMxOWYyLDIwMjYwNzExLDIwMjYtMDctMTFUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxvdmVycmlkZSw2NjAuMCwsUDIsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KMDFmZDNhNTktYmQwYi01NTAxLWI3MjItNDM3NDRjYWNlNjI5LDkyOTMyZjI1LThlNGEtNWUxNy1hMmI2LWYzNTVlMmY3OWZlZCwyMDI2MDcxMywyMDI2LTA3LTEzVDEzOjAwOjAwKzAwOjAwLHJldmlld2VyOjMsZXNjYWxhdGUsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQozYzVmNzNiNy02ZTM4LTVjM2ItOTQxYi1kYWZmZDVjMGUxMDgsMWZhODJmODUtNjk0ZC01Y2QwLWFhOGItMjA2ZmFlNzg5OWVkLDIwMjYwNzE0LDIwMjYtMDctMTRUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxlc2NhbGF0ZSwzMDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCjZjMTM5ODhkLTYyNGQtNTMxMC05NDU4LTk3YzFiZjcxNmYyOCxiYmVmYjc0Mi0xMDI1LTUwZjEtOWM4Zi1jOWRlOTAwZDFkZDUsMjAyNjA4MDEsMjAyNi0wOC0wMVQxNjowMDowMCswMDowMCxyZXZpZXdlcjoyLG92ZXJyaWRlLDQyMC4wLHdhc3RlX2xpdHRlciwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KZTg4ZmQ4NDktMzM0Ni01MWMwLWI0NzAtNjAzMjI0ZWZlNzZkLDA2NDE0MzQ0LTVmZmMtNTUyNy05YzY0LTVlZmEwZTc4OGZmMiwyMDI2MDgwMiwyMDI2LTA4LTAyVDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjMsZXNjYWxhdGUsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQplNjA4NDRhYi03MmQ5LTVhMWYtYjk3MC0xYmFlNjQ0YmQ5OTYsMmUwYWE0M2ItMzBhMy01NzM5LWI3MWYtZWJkMzYyNWZlZmYyLDIwMjYwODA0LDIwMjYtMDgtMDRUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxvdmVycmlkZSw2MDAuMCwsUDIsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KYjk3ODRjMTItZmFkOS01ZDE3LWE5YWMtOThjMzBjYmYxYzU5LDE2MGNlYzQzLTg5ZDAtNTMyZC1iNTY4LTk3NGZjY2E2YWY2MiwyMDI2MDgwNSwyMDI2LTA4LTA1VDIwOjAwOjAwKzAwOjAwLHJldmlld2VyOjIsb3ZlcnJpZGUsNjYwLjAsd2FzdGVfbGl0dGVyLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo5ZTFhM2MyMS0xYmIxLTVhZjAtOGNiNC0yOTBmNDAxMzFkY2MsMjM1OWFmOWMtYWQ3OS01M2VkLTk3ZDAtM2E2MmY1ZmY4ODZiLDIwMjYwODA3LDIwMjYtMDgtMDdUMTM6MDA6MDArMDA6MDAscmV2aWV3ZXI6NCxhY2NlcHQsMjQwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQowOTFkZTA0Mi1mYjkxLTUwMDAtODAzMy0zYTIxMDNiODdkMTAsYTU0YmYzOGYtODAwZC01YzY3LThhNzItNWU1MjkwYWZlNWQzLDIwMjYwODA4LDIwMjYtMDgtMDhUMTQ6MDA6MDArMDA6MDAscmV2aWV3ZXI6MSxlc2NhbGF0ZSwzMDAuMCwsLCxzeW50aGV0aWNfb3BlcmF0aW9uYWwNCmEzNDU4MGM3LWJhNTAtNThkOS05YjQ0LWFiMTU5MWZkMzM3MiwxZjkzOTlmNC1lYzA2LTVmNzUtYTNjNC1jNDA1MjE0Zjg2Y2EsMjAyNjA4MTAsMjAyNi0wOC0xMFQxNjowMDowMCswMDowMCxyZXZpZXdlcjozLGVzY2FsYXRlLDQyMC4wLCwsLHN5bnRoZXRpY19vcGVyYXRpb25hbA0KYzdhYmFlNTYtYTQzYi01NDI0LTkwNjctYWVlOTQ2MzFiOTA4LGIxZTE4Y2YzLThkZTktNTRlMC1iMTBjLWRkMmRlNDk2ZDhlNiwyMDI2MDgxMSwyMDI2LTA4LTExVDE3OjAwOjAwKzAwOjAwLHJldmlld2VyOjQsZXNjYWxhdGUsNDgwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo2NjhiMjAxNy0wNWE0LTVmM2MtYTZmYi04ZWZmNjc0MTRkNWEsYmVmZTkyMmUtZGQzOC01M2Q3LWJjODgtYzZmODc2MGZhMGZjLDIwMjYwODEzLDIwMjYtMDgtMTNUMTk6MDA6MDArMDA6MDAscmV2aWV3ZXI6MixhY2NlcHQsNjAwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo4YTAzNzMwZS0zMzJiLTU2YzEtYjkwNy05NDJlNzdjYzUxOTMsM2EzNDE4MzQtNTYwZi01NzE5LThmMDAtOTNjNTRlMjYzYWQ3LDIwMjYwODE0LDIwMjYtMDgtMTRUMjA6MDA6MDArMDA6MDAscmV2aWV3ZXI6MyxhY2NlcHQsNjYwLjAsLCwsc3ludGhldGljX29wZXJhdGlvbmFsDQo=", BinaryEncoding.Base64),
			    Raw = Csv.Document(Binary, [Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Headers = Table.PromoteHeaders(Raw, [PromoteAllScalars=true]),
			    Selected = Table.SelectColumns(Headers, {"decision_key", "date_key", "review_action", "review_lag_minutes", "data_truth_class"}),
			    Typed = Table.TransformColumnTypes(Selected, {{"decision_key", type text}, {"date_key", Int64.Type}, {"review_action", type text}, {"review_lag_minutes", type number}, {"data_truth_class", type text}}, "en-AU")
			in
			    Typed

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation
